<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/settings.proto

namespace Zitadel\Settings\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.settings.v1.EmailProviderSMTP</code>
 */
class EmailProviderSMTP extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sender_address = 1 [json_name = "senderAddress", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $sender_address = '';
    /**
     * Generated from protobuf field <code>string sender_name = 2 [json_name = "senderName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $sender_name = '';
    /**
     * Generated from protobuf field <code>bool tls = 3 [json_name = "tls"];</code>
     */
    protected $tls = false;
    /**
     * Generated from protobuf field <code>string host = 4 [json_name = "host", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $host = '';
    /**
     * Generated from protobuf field <code>string user = 5 [json_name = "user", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>string reply_to_address = 6 [json_name = "replyToAddress", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $reply_to_address = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sender_address
     *     @type string $sender_name
     *     @type bool $tls
     *     @type string $host
     *     @type string $user
     *     @type string $reply_to_address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Settings::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sender_address = 1 [json_name = "senderAddress", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getSenderAddress()
    {
        return $this->sender_address;
    }

    /**
     * Generated from protobuf field <code>string sender_address = 1 [json_name = "senderAddress", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSenderAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->sender_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sender_name = 2 [json_name = "senderName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getSenderName()
    {
        return $this->sender_name;
    }

    /**
     * Generated from protobuf field <code>string sender_name = 2 [json_name = "senderName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSenderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->sender_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool tls = 3 [json_name = "tls"];</code>
     * @return bool
     */
    public function getTls()
    {
        return $this->tls;
    }

    /**
     * Generated from protobuf field <code>bool tls = 3 [json_name = "tls"];</code>
     * @param bool $var
     * @return $this
     */
    public function setTls($var)
    {
        GPBUtil::checkBool($var);
        $this->tls = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string host = 4 [json_name = "host", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 4 [json_name = "host", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 5 [json_name = "user", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 5 [json_name = "user", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reply_to_address = 6 [json_name = "replyToAddress", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getReplyToAddress()
    {
        return $this->reply_to_address;
    }

    /**
     * Generated from protobuf field <code>string reply_to_address = 6 [json_name = "replyToAddress", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setReplyToAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->reply_to_address = $var;

        return $this;
    }

}

