<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/settings.proto

namespace Zitadel\Settings\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.settings.v1.SecretGeneratorQuery</code>
 */
class SecretGeneratorQuery extends \Google\Protobuf\Internal\Message
{
    protected $query;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Settings\V1\SecretGeneratorTypeQuery $type_query
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Settings::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.settings.v1.SecretGeneratorTypeQuery type_query = 1 [json_name = "typeQuery"];</code>
     * @return \Zitadel\Settings\V1\SecretGeneratorTypeQuery|null
     */
    public function getTypeQuery()
    {
        return $this->readOneof(1);
    }

    public function hasTypeQuery()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.zitadel.settings.v1.SecretGeneratorTypeQuery type_query = 1 [json_name = "typeQuery"];</code>
     * @param \Zitadel\Settings\V1\SecretGeneratorTypeQuery $var
     * @return $this
     */
    public function setTypeQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Settings\V1\SecretGeneratorTypeQuery::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getQuery()
    {
        return $this->whichOneof("query");
    }

}

