<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/webkey/v3alpha/config.proto

namespace Zitadel\Resources\Webkey\V3alpha\WebKeyRSAConfig;

use UnexpectedValueException;

/**
 * Protobuf type <code>zitadel.resources.webkey.v3alpha.WebKeyRSAConfig.RSAHasher</code>
 */
class RSAHasher
{
    /**
     * Generated from protobuf enum <code>RSA_HASHER_UNSPECIFIED = 0;</code>
     */
    const RSA_HASHER_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>RSA_HASHER_SHA256 = 1;</code>
     */
    const RSA_HASHER_SHA256 = 1;
    /**
     * Generated from protobuf enum <code>RSA_HASHER_SHA384 = 2;</code>
     */
    const RSA_HASHER_SHA384 = 2;
    /**
     * Generated from protobuf enum <code>RSA_HASHER_SHA512 = 3;</code>
     */
    const RSA_HASHER_SHA512 = 3;

    private static $valueToName = [
        self::RSA_HASHER_UNSPECIFIED => 'RSA_HASHER_UNSPECIFIED',
        self::RSA_HASHER_SHA256 => 'RSA_HASHER_SHA256',
        self::RSA_HASHER_SHA384 => 'RSA_HASHER_SHA384',
        self::RSA_HASHER_SHA512 => 'RSA_HASHER_SHA512',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

