<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/admin.proto

namespace Zitadel\Admin\V1\ExportDataRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.admin.v1.ExportDataRequest.GCSOutput</code>
 */
class GCSOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string bucket = 1 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $bucket = '';
    /**
     * Generated from protobuf field <code>string serviceaccount_json = 2 [json_name = "serviceaccountJson", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $serviceaccount_json = '';
    /**
     * Generated from protobuf field <code>string path = 3 [json_name = "path", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $path = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bucket
     *     @type string $serviceaccount_json
     *     @type string $path
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string bucket = 1 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>string bucket = 1 [json_name = "bucket", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setBucket($var)
    {
        GPBUtil::checkString($var, True);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serviceaccount_json = 2 [json_name = "serviceaccountJson", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getServiceaccountJson()
    {
        return $this->serviceaccount_json;
    }

    /**
     * Generated from protobuf field <code>string serviceaccount_json = 2 [json_name = "serviceaccountJson", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setServiceaccountJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->serviceaccount_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 3 [json_name = "path", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 3 [json_name = "path", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

}

