<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/admin.proto

namespace Zitadel\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.admin.v1.FailedEvent</code>
 */
class FailedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string database = 1 [json_name = "database", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $database = '';
    /**
     * Generated from protobuf field <code>string view_name = 2 [json_name = "viewName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $view_name = '';
    /**
     * Generated from protobuf field <code>uint64 failed_sequence = 3 [json_name = "failedSequence", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $failed_sequence = 0;
    /**
     * Generated from protobuf field <code>uint64 failure_count = 4 [json_name = "failureCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $failure_count = 0;
    /**
     * Generated from protobuf field <code>string error_message = 5 [json_name = "errorMessage", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $error_message = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_failed = 6 [json_name = "lastFailed", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $last_failed = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $database
     *     @type string $view_name
     *     @type int|string $failed_sequence
     *     @type int|string $failure_count
     *     @type string $error_message
     *     @type \Google\Protobuf\Timestamp $last_failed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string database = 1 [json_name = "database", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * Generated from protobuf field <code>string database = 1 [json_name = "database", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setDatabase($var)
    {
        GPBUtil::checkString($var, True);
        $this->database = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string view_name = 2 [json_name = "viewName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getViewName()
    {
        return $this->view_name;
    }

    /**
     * Generated from protobuf field <code>string view_name = 2 [json_name = "viewName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setViewName($var)
    {
        GPBUtil::checkString($var, True);
        $this->view_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 failed_sequence = 3 [json_name = "failedSequence", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int|string
     */
    public function getFailedSequence()
    {
        return $this->failed_sequence;
    }

    /**
     * Generated from protobuf field <code>uint64 failed_sequence = 3 [json_name = "failedSequence", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int|string $var
     * @return $this
     */
    public function setFailedSequence($var)
    {
        GPBUtil::checkUint64($var);
        $this->failed_sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 failure_count = 4 [json_name = "failureCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int|string
     */
    public function getFailureCount()
    {
        return $this->failure_count;
    }

    /**
     * Generated from protobuf field <code>uint64 failure_count = 4 [json_name = "failureCount", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int|string $var
     * @return $this
     */
    public function setFailureCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->failure_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 5 [json_name = "errorMessage", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 5 [json_name = "errorMessage", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_failed = 6 [json_name = "lastFailed", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLastFailed()
    {
        return $this->last_failed;
    }

    public function hasLastFailed()
    {
        return isset($this->last_failed);
    }

    public function clearLastFailed()
    {
        unset($this->last_failed);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_failed = 6 [json_name = "lastFailed", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastFailed($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_failed = $var;

        return $this;
    }

}

