<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/admin.proto

namespace Zitadel\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.admin.v1.IDPQuery</code>
 */
class IDPQuery extends \Google\Protobuf\Internal\Message
{
    protected $query;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Idp\V1\IDPIDQuery $idp_id_query
     *     @type \Zitadel\Idp\V1\IDPNameQuery $idp_name_query
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.idp.v1.IDPIDQuery idp_id_query = 1 [json_name = "idpIdQuery"];</code>
     * @return \Zitadel\Idp\V1\IDPIDQuery|null
     */
    public function getIdpIdQuery()
    {
        return $this->readOneof(1);
    }

    public function hasIdpIdQuery()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.zitadel.idp.v1.IDPIDQuery idp_id_query = 1 [json_name = "idpIdQuery"];</code>
     * @param \Zitadel\Idp\V1\IDPIDQuery $var
     * @return $this
     */
    public function setIdpIdQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Idp\V1\IDPIDQuery::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.idp.v1.IDPNameQuery idp_name_query = 2 [json_name = "idpNameQuery"];</code>
     * @return \Zitadel\Idp\V1\IDPNameQuery|null
     */
    public function getIdpNameQuery()
    {
        return $this->readOneof(2);
    }

    public function hasIdpNameQuery()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.zitadel.idp.v1.IDPNameQuery idp_name_query = 2 [json_name = "idpNameQuery"];</code>
     * @param \Zitadel\Idp\V1\IDPNameQuery $var
     * @return $this
     */
    public function setIdpNameQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Idp\V1\IDPNameQuery::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getQuery()
    {
        return $this->whichOneof("query");
    }

}

