<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/admin.proto

namespace Zitadel\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.admin.v1.ImportDataResponse</code>
 */
class ImportDataResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .zitadel.admin.v1.ImportDataError errors = 1 [json_name = "errors"];</code>
     */
    private $errors;
    /**
     * Generated from protobuf field <code>.zitadel.admin.v1.ImportDataSuccess success = 2 [json_name = "success"];</code>
     */
    protected $success = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Zitadel\Admin\V1\ImportDataError>|\Google\Protobuf\Internal\RepeatedField $errors
     *     @type \Zitadel\Admin\V1\ImportDataSuccess $success
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.admin.v1.ImportDataError errors = 1 [json_name = "errors"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.admin.v1.ImportDataError errors = 1 [json_name = "errors"];</code>
     * @param array<\Zitadel\Admin\V1\ImportDataError>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zitadel\Admin\V1\ImportDataError::class);
        $this->errors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.admin.v1.ImportDataSuccess success = 2 [json_name = "success"];</code>
     * @return \Zitadel\Admin\V1\ImportDataSuccess|null
     */
    public function getSuccess()
    {
        return $this->success;
    }

    public function hasSuccess()
    {
        return isset($this->success);
    }

    public function clearSuccess()
    {
        unset($this->success);
    }

    /**
     * Generated from protobuf field <code>.zitadel.admin.v1.ImportDataSuccess success = 2 [json_name = "success"];</code>
     * @param \Zitadel\Admin\V1\ImportDataSuccess $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Admin\V1\ImportDataSuccess::class);
        $this->success = $var;

        return $this;
    }

}

