<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/admin.proto

namespace Zitadel\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.admin.v1.ImportDataOrg</code>
 */
class ImportDataOrg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .zitadel.admin.v1.DataOrg orgs = 1 [json_name = "orgs"];</code>
     */
    private $orgs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Zitadel\Admin\V1\DataOrg>|\Google\Protobuf\Internal\RepeatedField $orgs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.admin.v1.DataOrg orgs = 1 [json_name = "orgs"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrgs()
    {
        return $this->orgs;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.admin.v1.DataOrg orgs = 1 [json_name = "orgs"];</code>
     * @param array<\Zitadel\Admin\V1\DataOrg>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zitadel\Admin\V1\DataOrg::class);
        $this->orgs = $arr;

        return $this;
    }

}

