<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/admin.proto

namespace Zitadel\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.admin.v1.UpdateLockoutPolicyRequest</code>
 */
class UpdateLockoutPolicyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * failed attempts until a user gets locked
     *
     * Generated from protobuf field <code>uint32 max_password_attempts = 1 [json_name = "maxPasswordAttempts", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $max_password_attempts = 0;
    /**
     * Generated from protobuf field <code>uint32 max_otp_attempts = 2 [json_name = "maxOtpAttempts", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $max_otp_attempts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $max_password_attempts
     *           failed attempts until a user gets locked
     *     @type int $max_otp_attempts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * failed attempts until a user gets locked
     *
     * Generated from protobuf field <code>uint32 max_password_attempts = 1 [json_name = "maxPasswordAttempts", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int
     */
    public function getMaxPasswordAttempts()
    {
        return $this->max_password_attempts;
    }

    /**
     * failed attempts until a user gets locked
     *
     * Generated from protobuf field <code>uint32 max_password_attempts = 1 [json_name = "maxPasswordAttempts", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int $var
     * @return $this
     */
    public function setMaxPasswordAttempts($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_password_attempts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_otp_attempts = 2 [json_name = "maxOtpAttempts", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int
     */
    public function getMaxOtpAttempts()
    {
        return $this->max_otp_attempts;
    }

    /**
     * Generated from protobuf field <code>uint32 max_otp_attempts = 2 [json_name = "maxOtpAttempts", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int $var
     * @return $this
     */
    public function setMaxOtpAttempts($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_otp_attempts = $var;

        return $this;
    }

}

