<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/admin.proto

namespace Zitadel\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.admin.v1.UpdateSecretGeneratorRequest</code>
 */
class UpdateSecretGeneratorRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zitadel.settings.v1.SecretGeneratorType generator_type = 1 [json_name = "generatorType", (.validate.rules) = {</code>
     */
    protected $generator_type = 0;
    /**
     * Generated from protobuf field <code>uint32 length = 2 [json_name = "length", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $length = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration expiry = 3 [json_name = "expiry", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $expiry = null;
    /**
     * Generated from protobuf field <code>bool include_lower_letters = 4 [json_name = "includeLowerLetters"];</code>
     */
    protected $include_lower_letters = false;
    /**
     * Generated from protobuf field <code>bool include_upper_letters = 5 [json_name = "includeUpperLetters"];</code>
     */
    protected $include_upper_letters = false;
    /**
     * Generated from protobuf field <code>bool include_digits = 6 [json_name = "includeDigits"];</code>
     */
    protected $include_digits = false;
    /**
     * Generated from protobuf field <code>bool include_symbols = 7 [json_name = "includeSymbols"];</code>
     */
    protected $include_symbols = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $generator_type
     *     @type int $length
     *     @type \Google\Protobuf\Duration $expiry
     *     @type bool $include_lower_letters
     *     @type bool $include_upper_letters
     *     @type bool $include_digits
     *     @type bool $include_symbols
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.settings.v1.SecretGeneratorType generator_type = 1 [json_name = "generatorType", (.validate.rules) = {</code>
     * @return int
     */
    public function getGeneratorType()
    {
        return $this->generator_type;
    }

    /**
     * Generated from protobuf field <code>.zitadel.settings.v1.SecretGeneratorType generator_type = 1 [json_name = "generatorType", (.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setGeneratorType($var)
    {
        GPBUtil::checkEnum($var, \Zitadel\Settings\V1\SecretGeneratorType::class);
        $this->generator_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 length = 2 [json_name = "length", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Generated from protobuf field <code>uint32 length = 2 [json_name = "length", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration expiry = 3 [json_name = "expiry", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getExpiry()
    {
        return $this->expiry;
    }

    public function hasExpiry()
    {
        return isset($this->expiry);
    }

    public function clearExpiry()
    {
        unset($this->expiry);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration expiry = 3 [json_name = "expiry", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setExpiry($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->expiry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_lower_letters = 4 [json_name = "includeLowerLetters"];</code>
     * @return bool
     */
    public function getIncludeLowerLetters()
    {
        return $this->include_lower_letters;
    }

    /**
     * Generated from protobuf field <code>bool include_lower_letters = 4 [json_name = "includeLowerLetters"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeLowerLetters($var)
    {
        GPBUtil::checkBool($var);
        $this->include_lower_letters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_upper_letters = 5 [json_name = "includeUpperLetters"];</code>
     * @return bool
     */
    public function getIncludeUpperLetters()
    {
        return $this->include_upper_letters;
    }

    /**
     * Generated from protobuf field <code>bool include_upper_letters = 5 [json_name = "includeUpperLetters"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeUpperLetters($var)
    {
        GPBUtil::checkBool($var);
        $this->include_upper_letters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_digits = 6 [json_name = "includeDigits"];</code>
     * @return bool
     */
    public function getIncludeDigits()
    {
        return $this->include_digits;
    }

    /**
     * Generated from protobuf field <code>bool include_digits = 6 [json_name = "includeDigits"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeDigits($var)
    {
        GPBUtil::checkBool($var);
        $this->include_digits = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_symbols = 7 [json_name = "includeSymbols"];</code>
     * @return bool
     */
    public function getIncludeSymbols()
    {
        return $this->include_symbols;
    }

    /**
     * Generated from protobuf field <code>bool include_symbols = 7 [json_name = "includeSymbols"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeSymbols($var)
    {
        GPBUtil::checkBool($var);
        $this->include_symbols = $var;

        return $this;
    }

}

