<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/milestone/v1/milestone.proto

namespace Zitadel\Milestone\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.milestone.v1.IsReachedQuery</code>
 */
class IsReachedQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool reached = 1 [json_name = "reached", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $reached = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $reached
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Milestone\V1\Milestone::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool reached = 1 [json_name = "reached", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return bool
     */
    public function getReached()
    {
        return $this->reached;
    }

    /**
     * Generated from protobuf field <code>bool reached = 1 [json_name = "reached", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param bool $var
     * @return $this
     */
    public function setReached($var)
    {
        GPBUtil::checkBool($var);
        $this->reached = $var;

        return $this;
    }

}

