<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/oidc/v2beta/authorization.proto

namespace Zitadel\Oidc\V2beta;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.oidc.v2beta.AuthRequest</code>
 */
class AuthRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp creation_date = 2 [json_name = "creationDate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $creation_date = null;
    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>repeated string scope = 4 [json_name = "scope", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $scope;
    /**
     * Generated from protobuf field <code>string redirect_uri = 5 [json_name = "redirectUri", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $redirect_uri = '';
    /**
     * Generated from protobuf field <code>repeated .zitadel.oidc.v2beta.Prompt prompt = 6 [json_name = "prompt", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $prompt;
    /**
     * Generated from protobuf field <code>repeated string ui_locales = 7 [json_name = "uiLocales", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $ui_locales;
    /**
     * Generated from protobuf field <code>optional string login_hint = 8 [json_name = "loginHint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $login_hint = null;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.Duration max_age = 9 [json_name = "maxAge", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $max_age = null;
    /**
     * Generated from protobuf field <code>optional string hint_user_id = 10 [json_name = "hintUserId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $hint_user_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Google\Protobuf\Timestamp $creation_date
     *     @type string $client_id
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $scope
     *     @type string $redirect_uri
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $prompt
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $ui_locales
     *     @type string $login_hint
     *     @type \Google\Protobuf\Duration $max_age
     *     @type string $hint_user_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Oidc\V2Beta\Authorization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp creation_date = 2 [json_name = "creationDate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }

    public function hasCreationDate()
    {
        return isset($this->creation_date);
    }

    public function clearCreationDate()
    {
        unset($this->creation_date);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp creation_date = 2 [json_name = "creationDate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreationDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->creation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string scope = 4 [json_name = "scope", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>repeated string scope = 4 [json_name = "scope", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScope($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scope = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string redirect_uri = 5 [json_name = "redirectUri", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getRedirectUri()
    {
        return $this->redirect_uri;
    }

    /**
     * Generated from protobuf field <code>string redirect_uri = 5 [json_name = "redirectUri", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setRedirectUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->redirect_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.oidc.v2beta.Prompt prompt = 6 [json_name = "prompt", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrompt()
    {
        return $this->prompt;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.oidc.v2beta.Prompt prompt = 6 [json_name = "prompt", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrompt($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Zitadel\Oidc\V2beta\Prompt::class);
        $this->prompt = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ui_locales = 7 [json_name = "uiLocales", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUiLocales()
    {
        return $this->ui_locales;
    }

    /**
     * Generated from protobuf field <code>repeated string ui_locales = 7 [json_name = "uiLocales", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUiLocales($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ui_locales = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string login_hint = 8 [json_name = "loginHint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getLoginHint()
    {
        return isset($this->login_hint) ? $this->login_hint : '';
    }

    public function hasLoginHint()
    {
        return isset($this->login_hint);
    }

    public function clearLoginHint()
    {
        unset($this->login_hint);
    }

    /**
     * Generated from protobuf field <code>optional string login_hint = 8 [json_name = "loginHint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setLoginHint($var)
    {
        GPBUtil::checkString($var, True);
        $this->login_hint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Duration max_age = 9 [json_name = "maxAge", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getMaxAge()
    {
        return $this->max_age;
    }

    public function hasMaxAge()
    {
        return isset($this->max_age);
    }

    public function clearMaxAge()
    {
        unset($this->max_age);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Duration max_age = 9 [json_name = "maxAge", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setMaxAge($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->max_age = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string hint_user_id = 10 [json_name = "hintUserId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getHintUserId()
    {
        return isset($this->hint_user_id) ? $this->hint_user_id : '';
    }

    public function hasHintUserId()
    {
        return isset($this->hint_user_id);
    }

    public function clearHintUserId()
    {
        unset($this->hint_user_id);
    }

    /**
     * Generated from protobuf field <code>optional string hint_user_id = 10 [json_name = "hintUserId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setHintUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->hint_user_id = $var;

        return $this;
    }

}

