<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/policy.proto

namespace Zitadel\Policy\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.policy.v1.PasswordAgePolicy</code>
 */
class PasswordAgePolicy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 1 [json_name = "details"];</code>
     */
    protected $details = null;
    /**
     * Amount of days after which a password will expire. The user will be forced to change the password on the following authentication.
     *
     * Generated from protobuf field <code>uint64 max_age_days = 2 [json_name = "maxAgeDays", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $max_age_days = 0;
    /**
     * Amount of days after which the user should be notified of the upcoming expiry. ZITADEL will not notify the user.
     *
     * Generated from protobuf field <code>uint64 expire_warn_days = 3 [json_name = "expireWarnDays", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $expire_warn_days = 0;
    /**
     * If true, the returned values represent the instance settings, e.g. by an organization without custom settings.
     *
     * Generated from protobuf field <code>bool is_default = 4 [json_name = "isDefault"];</code>
     */
    protected $is_default = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\V1\ObjectDetails $details
     *     @type int|string $max_age_days
     *           Amount of days after which a password will expire. The user will be forced to change the password on the following authentication.
     *     @type int|string $expire_warn_days
     *           Amount of days after which the user should be notified of the upcoming expiry. ZITADEL will not notify the user.
     *     @type bool $is_default
     *           If true, the returned values represent the instance settings, e.g. by an organization without custom settings.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 1 [json_name = "details"];</code>
     * @return \Zitadel\V1\ObjectDetails|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 1 [json_name = "details"];</code>
     * @param \Zitadel\V1\ObjectDetails $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\V1\ObjectDetails::class);
        $this->details = $var;

        return $this;
    }

    /**
     * Amount of days after which a password will expire. The user will be forced to change the password on the following authentication.
     *
     * Generated from protobuf field <code>uint64 max_age_days = 2 [json_name = "maxAgeDays", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int|string
     */
    public function getMaxAgeDays()
    {
        return $this->max_age_days;
    }

    /**
     * Amount of days after which a password will expire. The user will be forced to change the password on the following authentication.
     *
     * Generated from protobuf field <code>uint64 max_age_days = 2 [json_name = "maxAgeDays", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxAgeDays($var)
    {
        GPBUtil::checkUint64($var);
        $this->max_age_days = $var;

        return $this;
    }

    /**
     * Amount of days after which the user should be notified of the upcoming expiry. ZITADEL will not notify the user.
     *
     * Generated from protobuf field <code>uint64 expire_warn_days = 3 [json_name = "expireWarnDays", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int|string
     */
    public function getExpireWarnDays()
    {
        return $this->expire_warn_days;
    }

    /**
     * Amount of days after which the user should be notified of the upcoming expiry. ZITADEL will not notify the user.
     *
     * Generated from protobuf field <code>uint64 expire_warn_days = 3 [json_name = "expireWarnDays", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireWarnDays($var)
    {
        GPBUtil::checkUint64($var);
        $this->expire_warn_days = $var;

        return $this;
    }

    /**
     * If true, the returned values represent the instance settings, e.g. by an organization without custom settings.
     *
     * Generated from protobuf field <code>bool is_default = 4 [json_name = "isDefault"];</code>
     * @return bool
     */
    public function getIsDefault()
    {
        return $this->is_default;
    }

    /**
     * If true, the returned values represent the instance settings, e.g. by an organization without custom settings.
     *
     * Generated from protobuf field <code>bool is_default = 4 [json_name = "isDefault"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefault($var)
    {
        GPBUtil::checkBool($var);
        $this->is_default = $var;

        return $this;
    }

}

