<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/project.proto

namespace Zitadel\Project\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.project.v1.ProjectResourceOwnerQuery</code>
 */
class ProjectResourceOwnerQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string resource_owner = 1 [json_name = "resourceOwner", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $resource_owner = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $resource_owner
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Project::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string resource_owner = 1 [json_name = "resourceOwner", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getResourceOwner()
    {
        return $this->resource_owner;
    }

    /**
     * Generated from protobuf field <code>string resource_owner = 1 [json_name = "resourceOwner", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setResourceOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_owner = $var;

        return $this;
    }

}

