<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/management.proto

namespace Zitadel\Management\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.management.v1.AddOIDCAppResponse</code>
 */
class AddOIDCAppResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string app_id = 1 [json_name = "appId"];</code>
     */
    protected $app_id = '';
    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 2 [json_name = "details"];</code>
     */
    protected $details = null;
    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>string client_secret = 4 [json_name = "clientSecret", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $client_secret = '';
    /**
     * Generated from protobuf field <code>bool none_compliant = 5 [json_name = "noneCompliant"];</code>
     */
    protected $none_compliant = false;
    /**
     * Generated from protobuf field <code>repeated .zitadel.v1.LocalizedMessage compliance_problems = 6 [json_name = "complianceProblems"];</code>
     */
    private $compliance_problems;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $app_id
     *     @type \Zitadel\V1\ObjectDetails $details
     *     @type string $client_id
     *     @type string $client_secret
     *     @type bool $none_compliant
     *     @type array<\Zitadel\V1\LocalizedMessage>|\Google\Protobuf\Internal\RepeatedField $compliance_problems
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Management::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string app_id = 1 [json_name = "appId"];</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>string app_id = 1 [json_name = "appId"];</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 2 [json_name = "details"];</code>
     * @return \Zitadel\V1\ObjectDetails|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 2 [json_name = "details"];</code>
     * @param \Zitadel\V1\ObjectDetails $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\V1\ObjectDetails::class);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 4 [json_name = "clientSecret", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getClientSecret()
    {
        return $this->client_secret;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 4 [json_name = "clientSecret", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setClientSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool none_compliant = 5 [json_name = "noneCompliant"];</code>
     * @return bool
     */
    public function getNoneCompliant()
    {
        return $this->none_compliant;
    }

    /**
     * Generated from protobuf field <code>bool none_compliant = 5 [json_name = "noneCompliant"];</code>
     * @param bool $var
     * @return $this
     */
    public function setNoneCompliant($var)
    {
        GPBUtil::checkBool($var);
        $this->none_compliant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.v1.LocalizedMessage compliance_problems = 6 [json_name = "complianceProblems"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getComplianceProblems()
    {
        return $this->compliance_problems;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.v1.LocalizedMessage compliance_problems = 6 [json_name = "complianceProblems"];</code>
     * @param array<\Zitadel\V1\LocalizedMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setComplianceProblems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zitadel\V1\LocalizedMessage::class);
        $this->compliance_problems = $arr;

        return $this;
    }

}

