<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/management.proto

namespace Zitadel\Management\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.management.v1.ListProjectRolesRequest</code>
 */
class ListProjectRolesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string project_id = 1 [json_name = "projectId", (.validate.rules) = {</code>
     */
    protected $project_id = '';
    /**
     *list limitations and ordering
     *
     * Generated from protobuf field <code>.zitadel.v1.ListQuery query = 2 [json_name = "query"];</code>
     */
    protected $query = null;
    /**
     *criteria the client is looking for
     *
     * Generated from protobuf field <code>repeated .zitadel.project.v1.RoleQuery queries = 3 [json_name = "queries"];</code>
     */
    private $queries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $project_id
     *     @type \Zitadel\V1\ListQuery $query
     *          list limitations and ordering
     *     @type array<\Zitadel\Project\V1\RoleQuery>|\Google\Protobuf\Internal\RepeatedField $queries
     *          criteria the client is looking for
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Management::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string project_id = 1 [json_name = "projectId", (.validate.rules) = {</code>
     * @return string
     */
    public function getProjectId()
    {
        return $this->project_id;
    }

    /**
     * Generated from protobuf field <code>string project_id = 1 [json_name = "projectId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_id = $var;

        return $this;
    }

    /**
     *list limitations and ordering
     *
     * Generated from protobuf field <code>.zitadel.v1.ListQuery query = 2 [json_name = "query"];</code>
     * @return \Zitadel\V1\ListQuery|null
     */
    public function getQuery()
    {
        return $this->query;
    }

    public function hasQuery()
    {
        return isset($this->query);
    }

    public function clearQuery()
    {
        unset($this->query);
    }

    /**
     *list limitations and ordering
     *
     * Generated from protobuf field <code>.zitadel.v1.ListQuery query = 2 [json_name = "query"];</code>
     * @param \Zitadel\V1\ListQuery $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\V1\ListQuery::class);
        $this->query = $var;

        return $this;
    }

    /**
     *criteria the client is looking for
     *
     * Generated from protobuf field <code>repeated .zitadel.project.v1.RoleQuery queries = 3 [json_name = "queries"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQueries()
    {
        return $this->queries;
    }

    /**
     *criteria the client is looking for
     *
     * Generated from protobuf field <code>repeated .zitadel.project.v1.RoleQuery queries = 3 [json_name = "queries"];</code>
     * @param array<\Zitadel\Project\V1\RoleQuery>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQueries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zitadel\Project\V1\RoleQuery::class);
        $this->queries = $arr;

        return $this;
    }

}

