<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/saml/v2/authorization.proto

namespace GPBMetadata\Zitadel\Saml\V2;

class Authorization
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\ProtocGenOpenapiv2\Options\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD7\x0A\x0A#zitadel/saml/v2/authorization.proto\x12\x0Fzitadel.saml.v2\x1A\x1Fgoogle/protobuf/timestamp.proto\x1A.protoc-gen-openapiv2/options/annotations.proto\"\xCA\x05\x0A\x0BSAMLRequest\x12*\x0A\x02id\x18\x01 \x01(\x09B\x1A\x92A\x172\x15ID of the SAMLRequestR\x02id\x12k\x0A\x0Dcreation_date\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampB*\x92A'2%Time when the SAMLRequest was createdR\x0CcreationDate\x12Z\x0A\x06issuer\x18\x03 \x01(\x09BB\x92A?2=SAML entityID of the application that created the SAMLRequestR\x06issuer\x12\x8D\x01\x0A\x1Aassertion_consumer_service\x18\x04 \x01(\x09BO\x92AL2JURL which points back to the assertion consumer service of the applicationR\x18assertionConsumerService\x12\\\x0A\x0Brelay_state\x18\x05 \x01(\x09B;\x92A826RelayState provided by the application for the requestR\x0ArelayState\x12N\x0A\x07binding\x18\x06 \x01(\x09B4\x92A12/Binding used by the application for the requestR\x07binding:\x87\x01\x92A\x83\x01*\x80\x01\x0A*Find out more about SAMLRequest parameters\x12Rhttps://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html\"\x90\x01\x0A\x12AuthorizationError\x122\x0A\x05error\x18\x01 \x01(\x0E2\x1C.zitadel.saml.v2.ErrorReasonR\x05error\x120\x0A\x11error_description\x18\x02 \x01(\x09H\x00R\x10errorDescription\x88\x01\x01B\x14\x0A\x12_error_description*\xB1\x02\x0A\x0BErrorReason\x12\x1C\x0A\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\"\x0A\x1EERROR_REASON_VERSION_MISSMATCH\x10\x01\x12\x1E\x0A\x1AERROR_REASON_AUTH_N_FAILED\x10\x02\x12+\x0A'ERROR_REASON_INVALID_ATTR_NAME_OR_VALUE\x10\x03\x12&\x0A\"ERROR_REASON_INVALID_NAMEID_POLICY\x10\x04\x12\x1F\x0A\x1BERROR_REASON_REQUEST_DENIED\x10\x05\x12\$\x0A ERROR_REASON_REQUEST_UNSUPPORTED\x10\x06\x12\$\x0A ERROR_REASON_UNSUPPORTED_BINDING\x10\x07B2Z0github.com/zitadel/zitadel/pkg/grpc/saml/v2;samlb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

