<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/user/v3alpha/authenticator.proto

namespace Zitadel\Resources\User\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.user.v3alpha.IdentityProvider</code>
 */
class IdentityProvider extends \Google\Protobuf\Internal\Message
{
    /**
     * IDP ID is the read-only unique identifier of the identity provider in ZITADEL.
     *
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $idp_id = '';
    /**
     * IDP name is the name of the identity provider in ZITADEL.
     *
     * Generated from protobuf field <code>string idp_name = 3 [json_name = "idpName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $idp_name = '';
    /**
     * The user ID represents the ID provided by the identity provider.
     * This ID is used to link the user in ZITADEL with the identity provider.
     *
     * Generated from protobuf field <code>string user_id = 4 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $user_id = '';
    /**
     * The username represents the username provided by the identity provider.
     *
     * Generated from protobuf field <code>string username = 5 [json_name = "username", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $username = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $idp_id
     *           IDP ID is the read-only unique identifier of the identity provider in ZITADEL.
     *     @type string $idp_name
     *           IDP name is the name of the identity provider in ZITADEL.
     *     @type string $user_id
     *           The user ID represents the ID provided by the identity provider.
     *           This ID is used to link the user in ZITADEL with the identity provider.
     *     @type string $username
     *           The username represents the username provided by the identity provider.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\User\V3Alpha\Authenticator::initOnce();
        parent::__construct($data);
    }

    /**
     * IDP ID is the read-only unique identifier of the identity provider in ZITADEL.
     *
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getIdpId()
    {
        return $this->idp_id;
    }

    /**
     * IDP ID is the read-only unique identifier of the identity provider in ZITADEL.
     *
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIdpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->idp_id = $var;

        return $this;
    }

    /**
     * IDP name is the name of the identity provider in ZITADEL.
     *
     * Generated from protobuf field <code>string idp_name = 3 [json_name = "idpName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getIdpName()
    {
        return $this->idp_name;
    }

    /**
     * IDP name is the name of the identity provider in ZITADEL.
     *
     * Generated from protobuf field <code>string idp_name = 3 [json_name = "idpName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIdpName($var)
    {
        GPBUtil::checkString($var, True);
        $this->idp_name = $var;

        return $this;
    }

    /**
     * The user ID represents the ID provided by the identity provider.
     * This ID is used to link the user in ZITADEL with the identity provider.
     *
     * Generated from protobuf field <code>string user_id = 4 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * The user ID represents the ID provided by the identity provider.
     * This ID is used to link the user in ZITADEL with the identity provider.
     *
     * Generated from protobuf field <code>string user_id = 4 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * The username represents the username provided by the identity provider.
     *
     * Generated from protobuf field <code>string username = 5 [json_name = "username", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * The username represents the username provided by the identity provider.
     *
     * Generated from protobuf field <code>string username = 5 [json_name = "username", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

}

