<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/user/v3alpha/authenticator.proto

namespace Zitadel\Resources\User\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.user.v3alpha.IDPAuthenticator</code>
 */
class IDPAuthenticator extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the identity provider
     *
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $idp_id = '';
    /**
     * ID of the user provided by the identity provider
     *
     * Generated from protobuf field <code>string user_id = 2 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $user_id = '';
    /**
     * Username of the user provided by the identity provider.
     *
     * Generated from protobuf field <code>string user_name = 3 [json_name = "userName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $user_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $idp_id
     *           ID of the identity provider
     *     @type string $user_id
     *           ID of the user provided by the identity provider
     *     @type string $user_name
     *           Username of the user provided by the identity provider.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\User\V3Alpha\Authenticator::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the identity provider
     *
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getIdpId()
    {
        return $this->idp_id;
    }

    /**
     * ID of the identity provider
     *
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIdpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->idp_id = $var;

        return $this;
    }

    /**
     * ID of the user provided by the identity provider
     *
     * Generated from protobuf field <code>string user_id = 2 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * ID of the user provided by the identity provider
     *
     * Generated from protobuf field <code>string user_id = 2 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Username of the user provided by the identity provider.
     *
     * Generated from protobuf field <code>string user_name = 3 [json_name = "userName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     * Username of the user provided by the identity provider.
     *
     * Generated from protobuf field <code>string user_name = 3 [json_name = "userName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

}

