<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/user/v3alpha/authenticator.proto

namespace Zitadel\Resources\User\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.user.v3alpha.OTPSMS</code>
 */
class OTPSMS extends \Google\Protobuf\Internal\Message
{
    /**
     * unique identifier of the one-time password (OTP) SMS authenticator.
     *
     * Generated from protobuf field <code>string otp_sms_id = 1 [json_name = "otpSmsId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $otp_sms_id = '';
    /**
     * The phone number used for the OTP SMS authenticator.
     *
     * Generated from protobuf field <code>string phone = 2 [json_name = "phone", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $phone = '';
    /**
     * State whether the OTP SMS registration has been completed.
     *
     * Generated from protobuf field <code>bool is_verified = 3 [json_name = "isVerified"];</code>
     */
    protected $is_verified = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $otp_sms_id
     *           unique identifier of the one-time password (OTP) SMS authenticator.
     *     @type string $phone
     *           The phone number used for the OTP SMS authenticator.
     *     @type bool $is_verified
     *           State whether the OTP SMS registration has been completed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\User\V3Alpha\Authenticator::initOnce();
        parent::__construct($data);
    }

    /**
     * unique identifier of the one-time password (OTP) SMS authenticator.
     *
     * Generated from protobuf field <code>string otp_sms_id = 1 [json_name = "otpSmsId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getOtpSmsId()
    {
        return $this->otp_sms_id;
    }

    /**
     * unique identifier of the one-time password (OTP) SMS authenticator.
     *
     * Generated from protobuf field <code>string otp_sms_id = 1 [json_name = "otpSmsId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOtpSmsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->otp_sms_id = $var;

        return $this;
    }

    /**
     * The phone number used for the OTP SMS authenticator.
     *
     * Generated from protobuf field <code>string phone = 2 [json_name = "phone", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * The phone number used for the OTP SMS authenticator.
     *
     * Generated from protobuf field <code>string phone = 2 [json_name = "phone", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * State whether the OTP SMS registration has been completed.
     *
     * Generated from protobuf field <code>bool is_verified = 3 [json_name = "isVerified"];</code>
     * @return bool
     */
    public function getIsVerified()
    {
        return $this->is_verified;
    }

    /**
     * State whether the OTP SMS registration has been completed.
     *
     * Generated from protobuf field <code>bool is_verified = 3 [json_name = "isVerified"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->is_verified = $var;

        return $this;
    }

}

