<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/user/v3alpha/authenticator.proto

namespace Zitadel\Resources\User\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.user.v3alpha.SetUsername</code>
 */
class SetUsername extends \Google\Protobuf\Internal\Message
{
    /**
     * Set the user's username. This will be used for identification during authentication.
     *
     * Generated from protobuf field <code>string username = 1 [json_name = "username", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $username = '';
    /**
     * By default username must be unique across all organizations in an instance.
     * This option allow to restrict the uniqueness to the user's own organization.
     * As a result, this username can only be used if the authentication is limited
     * to the corresponding organization.
     * This can be useful if you provide multiple usernames for a single user, where one
     * if specific to your organization, e.g.:
     * - gigi-giraffe\@zitadel.com (unique across organizations)
     * - gigi-giraffe (unique only inside the ZITADEL organization)
     *
     * Generated from protobuf field <code>bool is_organization_specific = 2 [json_name = "isOrganizationSpecific"];</code>
     */
    protected $is_organization_specific = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $username
     *           Set the user's username. This will be used for identification during authentication.
     *     @type bool $is_organization_specific
     *           By default username must be unique across all organizations in an instance.
     *           This option allow to restrict the uniqueness to the user's own organization.
     *           As a result, this username can only be used if the authentication is limited
     *           to the corresponding organization.
     *           This can be useful if you provide multiple usernames for a single user, where one
     *           if specific to your organization, e.g.:
     *           - gigi-giraffe\@zitadel.com (unique across organizations)
     *           - gigi-giraffe (unique only inside the ZITADEL organization)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\User\V3Alpha\Authenticator::initOnce();
        parent::__construct($data);
    }

    /**
     * Set the user's username. This will be used for identification during authentication.
     *
     * Generated from protobuf field <code>string username = 1 [json_name = "username", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set the user's username. This will be used for identification during authentication.
     *
     * Generated from protobuf field <code>string username = 1 [json_name = "username", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * By default username must be unique across all organizations in an instance.
     * This option allow to restrict the uniqueness to the user's own organization.
     * As a result, this username can only be used if the authentication is limited
     * to the corresponding organization.
     * This can be useful if you provide multiple usernames for a single user, where one
     * if specific to your organization, e.g.:
     * - gigi-giraffe\@zitadel.com (unique across organizations)
     * - gigi-giraffe (unique only inside the ZITADEL organization)
     *
     * Generated from protobuf field <code>bool is_organization_specific = 2 [json_name = "isOrganizationSpecific"];</code>
     * @return bool
     */
    public function getIsOrganizationSpecific()
    {
        return $this->is_organization_specific;
    }

    /**
     * By default username must be unique across all organizations in an instance.
     * This option allow to restrict the uniqueness to the user's own organization.
     * As a result, this username can only be used if the authentication is limited
     * to the corresponding organization.
     * This can be useful if you provide multiple usernames for a single user, where one
     * if specific to your organization, e.g.:
     * - gigi-giraffe\@zitadel.com (unique across organizations)
     * - gigi-giraffe (unique only inside the ZITADEL organization)
     *
     * Generated from protobuf field <code>bool is_organization_specific = 2 [json_name = "isOrganizationSpecific"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOrganizationSpecific($var)
    {
        GPBUtil::checkBool($var);
        $this->is_organization_specific = $var;

        return $this;
    }

}

