<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/auth.proto

namespace Zitadel\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.auth.v1.RemoveMyLinkedIDPRequest</code>
 */
class RemoveMyLinkedIDPRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.validate.rules) = {</code>
     */
    protected $idp_id = '';
    /**
     * Generated from protobuf field <code>string linked_user_id = 2 [json_name = "linkedUserId", (.validate.rules) = {</code>
     */
    protected $linked_user_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $idp_id
     *     @type string $linked_user_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.validate.rules) = {</code>
     * @return string
     */
    public function getIdpId()
    {
        return $this->idp_id;
    }

    /**
     * Generated from protobuf field <code>string idp_id = 1 [json_name = "idpId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIdpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->idp_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string linked_user_id = 2 [json_name = "linkedUserId", (.validate.rules) = {</code>
     * @return string
     */
    public function getLinkedUserId()
    {
        return $this->linked_user_id;
    }

    /**
     * Generated from protobuf field <code>string linked_user_id = 2 [json_name = "linkedUserId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setLinkedUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->linked_user_id = $var;

        return $this;
    }

}

