<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/idp.proto

namespace Zitadel\Idp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.idp.v1.IDPOwnerTypeQuery</code>
 */
class IDPOwnerTypeQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zitadel.idp.v1.IDPOwnerType owner_type = 1 [json_name = "ownerType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $owner_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $owner_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Idp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.idp.v1.IDPOwnerType owner_type = 1 [json_name = "ownerType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int
     */
    public function getOwnerType()
    {
        return $this->owner_type;
    }

    /**
     * Generated from protobuf field <code>.zitadel.idp.v1.IDPOwnerType owner_type = 1 [json_name = "ownerType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int $var
     * @return $this
     */
    public function setOwnerType($var)
    {
        GPBUtil::checkEnum($var, \Zitadel\Idp\V1\IDPOwnerType::class);
        $this->owner_type = $var;

        return $this;
    }

}

