<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/org.proto

namespace Zitadel\Org\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>zitadel.org.v1.OrgState</code>
 */
class OrgState
{
    /**
     * Generated from protobuf enum <code>ORG_STATE_UNSPECIFIED = 0;</code>
     */
    const ORG_STATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>ORG_STATE_ACTIVE = 1;</code>
     */
    const ORG_STATE_ACTIVE = 1;
    /**
     * Generated from protobuf enum <code>ORG_STATE_INACTIVE = 2;</code>
     */
    const ORG_STATE_INACTIVE = 2;
    /**
     * Generated from protobuf enum <code>ORG_STATE_REMOVED = 3;</code>
     */
    const ORG_STATE_REMOVED = 3;

    private static $valueToName = [
        self::ORG_STATE_UNSPECIFIED => 'ORG_STATE_UNSPECIFIED',
        self::ORG_STATE_ACTIVE => 'ORG_STATE_ACTIVE',
        self::ORG_STATE_INACTIVE => 'ORG_STATE_INACTIVE',
        self::ORG_STATE_REMOVED => 'ORG_STATE_REMOVED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

