<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/userschema/v3alpha/user_schema.proto

namespace Zitadel\Resources\Userschema\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.userschema.v3alpha.IDFilter</code>
 */
class IDFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Defines the ID of the user schema to filter for.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $id = '';
    /**
     * Defines which text comparison method used for the id filter.
     *
     * Generated from protobuf field <code>.zitadel.resources.object.v3alpha.TextFilterMethod method = 2 [json_name = "method", (.validate.rules) = {</code>
     */
    protected $method = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Defines the ID of the user schema to filter for.
     *     @type int $method
     *           Defines which text comparison method used for the id filter.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Userschema\V3Alpha\UserSchema::initOnce();
        parent::__construct($data);
    }

    /**
     * Defines the ID of the user schema to filter for.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Defines the ID of the user schema to filter for.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Defines which text comparison method used for the id filter.
     *
     * Generated from protobuf field <code>.zitadel.resources.object.v3alpha.TextFilterMethod method = 2 [json_name = "method", (.validate.rules) = {</code>
     * @return int
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Defines which text comparison method used for the id filter.
     *
     * Generated from protobuf field <code>.zitadel.resources.object.v3alpha.TextFilterMethod method = 2 [json_name = "method", (.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkEnum($var, \Zitadel\Resources\Object\V3alpha\TextFilterMethod::class);
        $this->method = $var;

        return $this;
    }

}

