<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/userschema/v3alpha/user_schema.proto

namespace Zitadel\Resources\Userschema\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.userschema.v3alpha.NotFilter</code>
 */
class NotFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.SearchFilter filter = 1 [json_name = "filter", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $filter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Resources\Userschema\V3alpha\SearchFilter $filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Userschema\V3Alpha\UserSchema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.SearchFilter filter = 1 [json_name = "filter", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Zitadel\Resources\Userschema\V3alpha\SearchFilter|null
     */
    public function getFilter()
    {
        return $this->filter;
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.SearchFilter filter = 1 [json_name = "filter", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Zitadel\Resources\Userschema\V3alpha\SearchFilter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Userschema\V3alpha\SearchFilter::class);
        $this->filter = $var;

        return $this;
    }

}

