<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/userschema/v3alpha/user_schema_service.proto

namespace Zitadel\Resources\Userschema\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.userschema.v3alpha.PatchUserSchemaRequest</code>
 */
class PatchUserSchemaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $instance = null;
    /**
     * unique identifier of the schema.
     *
     * Generated from protobuf field <code>string id = 2 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.PatchUserSchema user_schema = 3 [json_name = "userSchema"];</code>
     */
    protected $user_schema = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Object\V3alpha\Instance $instance
     *     @type string $id
     *           unique identifier of the schema.
     *     @type \Zitadel\Resources\Userschema\V3alpha\PatchUserSchema $user_schema
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Userschema\V3Alpha\UserSchemaService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Zitadel\Object\V3alpha\Instance|null
     */
    public function getInstance()
    {
        return $this->instance;
    }

    public function hasInstance()
    {
        return isset($this->instance);
    }

    public function clearInstance()
    {
        unset($this->instance);
    }

    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Zitadel\Object\V3alpha\Instance $var
     * @return $this
     */
    public function setInstance($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Object\V3alpha\Instance::class);
        $this->instance = $var;

        return $this;
    }

    /**
     * unique identifier of the schema.
     *
     * Generated from protobuf field <code>string id = 2 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * unique identifier of the schema.
     *
     * Generated from protobuf field <code>string id = 2 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.PatchUserSchema user_schema = 3 [json_name = "userSchema"];</code>
     * @return \Zitadel\Resources\Userschema\V3alpha\PatchUserSchema|null
     */
    public function getUserSchema()
    {
        return $this->user_schema;
    }

    public function hasUserSchema()
    {
        return isset($this->user_schema);
    }

    public function clearUserSchema()
    {
        unset($this->user_schema);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.PatchUserSchema user_schema = 3 [json_name = "userSchema"];</code>
     * @param \Zitadel\Resources\Userschema\V3alpha\PatchUserSchema $var
     * @return $this
     */
    public function setUserSchema($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Userschema\V3alpha\PatchUserSchema::class);
        $this->user_schema = $var;

        return $this;
    }

}

