<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/userschema/v3alpha/user_schema.proto

namespace Zitadel\Resources\Userschema\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.userschema.v3alpha.SearchFilter</code>
 */
class SearchFilter extends \Google\Protobuf\Internal\Message
{
    protected $Filter;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Resources\Userschema\V3alpha\OrFilter $or_filter
     *           Union the results of each sub filter ('OR').
     *     @type \Zitadel\Resources\Userschema\V3alpha\AndFilter $and_filter
     *           Limit the result to match all sub queries ('AND').
     *           Note that if you specify multiple queries, they will be implicitly used as andQueries.
     *           Use the andFilter in combination with orFilter and notFilter.
     *     @type \Zitadel\Resources\Userschema\V3alpha\NotFilter $not_filter
     *           Exclude / Negate the result of the sub filter ('NOT').
     *     @type \Zitadel\Resources\Userschema\V3alpha\TypeFilter $type_filter
     *           Limit the result to a specific schema type.
     *     @type \Zitadel\Resources\Userschema\V3alpha\StateFilter $state_filter
     *           Limit the result to a specific state of the schema.
     *     @type \Zitadel\Resources\Userschema\V3alpha\IDFilter $id_filter
     *           Limit the result to a specific schema ID.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Userschema\V3Alpha\UserSchema::initOnce();
        parent::__construct($data);
    }

    /**
     * Union the results of each sub filter ('OR').
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.OrFilter or_filter = 1 [json_name = "orFilter"];</code>
     * @return \Zitadel\Resources\Userschema\V3alpha\OrFilter|null
     */
    public function getOrFilter()
    {
        return $this->readOneof(1);
    }

    public function hasOrFilter()
    {
        return $this->hasOneof(1);
    }

    /**
     * Union the results of each sub filter ('OR').
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.OrFilter or_filter = 1 [json_name = "orFilter"];</code>
     * @param \Zitadel\Resources\Userschema\V3alpha\OrFilter $var
     * @return $this
     */
    public function setOrFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Userschema\V3alpha\OrFilter::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Limit the result to match all sub queries ('AND').
     * Note that if you specify multiple queries, they will be implicitly used as andQueries.
     * Use the andFilter in combination with orFilter and notFilter.
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.AndFilter and_filter = 2 [json_name = "andFilter"];</code>
     * @return \Zitadel\Resources\Userschema\V3alpha\AndFilter|null
     */
    public function getAndFilter()
    {
        return $this->readOneof(2);
    }

    public function hasAndFilter()
    {
        return $this->hasOneof(2);
    }

    /**
     * Limit the result to match all sub queries ('AND').
     * Note that if you specify multiple queries, they will be implicitly used as andQueries.
     * Use the andFilter in combination with orFilter and notFilter.
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.AndFilter and_filter = 2 [json_name = "andFilter"];</code>
     * @param \Zitadel\Resources\Userschema\V3alpha\AndFilter $var
     * @return $this
     */
    public function setAndFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Userschema\V3alpha\AndFilter::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Exclude / Negate the result of the sub filter ('NOT').
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.NotFilter not_filter = 3 [json_name = "notFilter"];</code>
     * @return \Zitadel\Resources\Userschema\V3alpha\NotFilter|null
     */
    public function getNotFilter()
    {
        return $this->readOneof(3);
    }

    public function hasNotFilter()
    {
        return $this->hasOneof(3);
    }

    /**
     * Exclude / Negate the result of the sub filter ('NOT').
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.NotFilter not_filter = 3 [json_name = "notFilter"];</code>
     * @param \Zitadel\Resources\Userschema\V3alpha\NotFilter $var
     * @return $this
     */
    public function setNotFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Userschema\V3alpha\NotFilter::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Limit the result to a specific schema type.
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.TypeFilter type_filter = 5 [json_name = "typeFilter"];</code>
     * @return \Zitadel\Resources\Userschema\V3alpha\TypeFilter|null
     */
    public function getTypeFilter()
    {
        return $this->readOneof(5);
    }

    public function hasTypeFilter()
    {
        return $this->hasOneof(5);
    }

    /**
     * Limit the result to a specific schema type.
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.TypeFilter type_filter = 5 [json_name = "typeFilter"];</code>
     * @param \Zitadel\Resources\Userschema\V3alpha\TypeFilter $var
     * @return $this
     */
    public function setTypeFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Userschema\V3alpha\TypeFilter::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Limit the result to a specific state of the schema.
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.StateFilter state_filter = 6 [json_name = "stateFilter"];</code>
     * @return \Zitadel\Resources\Userschema\V3alpha\StateFilter|null
     */
    public function getStateFilter()
    {
        return $this->readOneof(6);
    }

    public function hasStateFilter()
    {
        return $this->hasOneof(6);
    }

    /**
     * Limit the result to a specific state of the schema.
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.StateFilter state_filter = 6 [json_name = "stateFilter"];</code>
     * @param \Zitadel\Resources\Userschema\V3alpha\StateFilter $var
     * @return $this
     */
    public function setStateFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Userschema\V3alpha\StateFilter::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Limit the result to a specific schema ID.
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.IDFilter id_filter = 7 [json_name = "idFilter"];</code>
     * @return \Zitadel\Resources\Userschema\V3alpha\IDFilter|null
     */
    public function getIdFilter()
    {
        return $this->readOneof(7);
    }

    public function hasIdFilter()
    {
        return $this->hasOneof(7);
    }

    /**
     * Limit the result to a specific schema ID.
     *
     * Generated from protobuf field <code>.zitadel.resources.userschema.v3alpha.IDFilter id_filter = 7 [json_name = "idFilter"];</code>
     * @param \Zitadel\Resources\Userschema\V3alpha\IDFilter $var
     * @return $this
     */
    public function setIdFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Userschema\V3alpha\IDFilter::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getFilter()
    {
        return $this->whichOneof("Filter");
    }

}

