<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/saml/v2/saml_service.proto

namespace Zitadel\Saml\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.saml.v2.PostResponse</code>
 */
class PostResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string relay_state = 1 [json_name = "relayState"];</code>
     */
    protected $relay_state = '';
    /**
     * Generated from protobuf field <code>string saml_response = 2 [json_name = "samlResponse"];</code>
     */
    protected $saml_response = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $relay_state
     *     @type string $saml_response
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Saml\V2\SamlService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string relay_state = 1 [json_name = "relayState"];</code>
     * @return string
     */
    public function getRelayState()
    {
        return $this->relay_state;
    }

    /**
     * Generated from protobuf field <code>string relay_state = 1 [json_name = "relayState"];</code>
     * @param string $var
     * @return $this
     */
    public function setRelayState($var)
    {
        GPBUtil::checkString($var, True);
        $this->relay_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string saml_response = 2 [json_name = "samlResponse"];</code>
     * @return string
     */
    public function getSamlResponse()
    {
        return $this->saml_response;
    }

    /**
     * Generated from protobuf field <code>string saml_response = 2 [json_name = "samlResponse"];</code>
     * @param string $var
     * @return $this
     */
    public function setSamlResponse($var)
    {
        GPBUtil::checkString($var, True);
        $this->saml_response = $var;

        return $this;
    }

}

