<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/saml/v2/authorization.proto

namespace Zitadel\Saml\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.saml.v2.SAMLRequest</code>
 */
class SAMLRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp creation_date = 2 [json_name = "creationDate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $creation_date = null;
    /**
     * Generated from protobuf field <code>string issuer = 3 [json_name = "issuer", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $issuer = '';
    /**
     * Generated from protobuf field <code>string assertion_consumer_service = 4 [json_name = "assertionConsumerService", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $assertion_consumer_service = '';
    /**
     * Generated from protobuf field <code>string relay_state = 5 [json_name = "relayState", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $relay_state = '';
    /**
     * Generated from protobuf field <code>string binding = 6 [json_name = "binding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $binding = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Google\Protobuf\Timestamp $creation_date
     *     @type string $issuer
     *     @type string $assertion_consumer_service
     *     @type string $relay_state
     *     @type string $binding
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Saml\V2\Authorization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp creation_date = 2 [json_name = "creationDate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }

    public function hasCreationDate()
    {
        return isset($this->creation_date);
    }

    public function clearCreationDate()
    {
        unset($this->creation_date);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp creation_date = 2 [json_name = "creationDate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreationDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->creation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string issuer = 3 [json_name = "issuer", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getIssuer()
    {
        return $this->issuer;
    }

    /**
     * Generated from protobuf field <code>string issuer = 3 [json_name = "issuer", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->issuer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string assertion_consumer_service = 4 [json_name = "assertionConsumerService", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getAssertionConsumerService()
    {
        return $this->assertion_consumer_service;
    }

    /**
     * Generated from protobuf field <code>string assertion_consumer_service = 4 [json_name = "assertionConsumerService", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setAssertionConsumerService($var)
    {
        GPBUtil::checkString($var, True);
        $this->assertion_consumer_service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string relay_state = 5 [json_name = "relayState", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getRelayState()
    {
        return $this->relay_state;
    }

    /**
     * Generated from protobuf field <code>string relay_state = 5 [json_name = "relayState", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setRelayState($var)
    {
        GPBUtil::checkString($var, True);
        $this->relay_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string binding = 6 [json_name = "binding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getBinding()
    {
        return $this->binding;
    }

    /**
     * Generated from protobuf field <code>string binding = 6 [json_name = "binding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setBinding($var)
    {
        GPBUtil::checkString($var, True);
        $this->binding = $var;

        return $this;
    }

}

