<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/oidc/v2/authorization.proto

namespace Zitadel\Oidc\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.oidc.v2.DeviceAuthorizationRequest</code>
 */
class DeviceAuthorizationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the device authorization request to be used for authorizing or denying the request.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * The client_id of the application that initiated the device authorization request.
     *
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     */
    protected $client_id = '';
    /**
     * The scopes requested by the application.
     *
     * Generated from protobuf field <code>repeated string scope = 3 [json_name = "scope"];</code>
     */
    private $scope;
    /**
     * Name of the client application.
     *
     * Generated from protobuf field <code>string app_name = 4 [json_name = "appName"];</code>
     */
    protected $app_name = '';
    /**
     * Name of the project the client application is part of.
     *
     * Generated from protobuf field <code>string project_name = 5 [json_name = "projectName"];</code>
     */
    protected $project_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           The unique identifier of the device authorization request to be used for authorizing or denying the request.
     *     @type string $client_id
     *           The client_id of the application that initiated the device authorization request.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $scope
     *           The scopes requested by the application.
     *     @type string $app_name
     *           Name of the client application.
     *     @type string $project_name
     *           Name of the project the client application is part of.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Oidc\V2\Authorization::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the device authorization request to be used for authorizing or denying the request.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * The unique identifier of the device authorization request to be used for authorizing or denying the request.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * The client_id of the application that initiated the device authorization request.
     *
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * The client_id of the application that initiated the device authorization request.
     *
     * Generated from protobuf field <code>string client_id = 2 [json_name = "clientId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * The scopes requested by the application.
     *
     * Generated from protobuf field <code>repeated string scope = 3 [json_name = "scope"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * The scopes requested by the application.
     *
     * Generated from protobuf field <code>repeated string scope = 3 [json_name = "scope"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScope($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scope = $arr;

        return $this;
    }

    /**
     * Name of the client application.
     *
     * Generated from protobuf field <code>string app_name = 4 [json_name = "appName"];</code>
     * @return string
     */
    public function getAppName()
    {
        return $this->app_name;
    }

    /**
     * Name of the client application.
     *
     * Generated from protobuf field <code>string app_name = 4 [json_name = "appName"];</code>
     * @param string $var
     * @return $this
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_name = $var;

        return $this;
    }

    /**
     * Name of the project the client application is part of.
     *
     * Generated from protobuf field <code>string project_name = 5 [json_name = "projectName"];</code>
     * @return string
     */
    public function getProjectName()
    {
        return $this->project_name;
    }

    /**
     * Name of the project the client application is part of.
     *
     * Generated from protobuf field <code>string project_name = 5 [json_name = "projectName"];</code>
     * @param string $var
     * @return $this
     */
    public function setProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_name = $var;

        return $this;
    }

}

