<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/debug_events/v3alpha/debug_events_service.proto

namespace Zitadel\Resources\Debug_events\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.debug_events.v3alpha.CreateDebugEventsRequest</code>
 */
class CreateDebugEventsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $instance = null;
    /**
     * unique identifier for the aggregate we want to push events to.
     *
     * Generated from protobuf field <code>string aggregate_id = 2 [json_name = "aggregateId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $aggregate_id = '';
    /**
     * Generated from protobuf field <code>repeated .zitadel.resources.debug_events.v3alpha.Event events = 3 [json_name = "events"];</code>
     */
    private $events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Object\V3alpha\Instance $instance
     *     @type string $aggregate_id
     *           unique identifier for the aggregate we want to push events to.
     *     @type array<\Zitadel\Resources\Debug_events\V3alpha\Event>|\Google\Protobuf\Internal\RepeatedField $events
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\DebugEvents\V3Alpha\DebugEventsService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Zitadel\Object\V3alpha\Instance|null
     */
    public function getInstance()
    {
        return $this->instance;
    }

    public function hasInstance()
    {
        return isset($this->instance);
    }

    public function clearInstance()
    {
        unset($this->instance);
    }

    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Zitadel\Object\V3alpha\Instance $var
     * @return $this
     */
    public function setInstance($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Object\V3alpha\Instance::class);
        $this->instance = $var;

        return $this;
    }

    /**
     * unique identifier for the aggregate we want to push events to.
     *
     * Generated from protobuf field <code>string aggregate_id = 2 [json_name = "aggregateId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getAggregateId()
    {
        return $this->aggregate_id;
    }

    /**
     * unique identifier for the aggregate we want to push events to.
     *
     * Generated from protobuf field <code>string aggregate_id = 2 [json_name = "aggregateId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setAggregateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->aggregate_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.resources.debug_events.v3alpha.Event events = 3 [json_name = "events"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.resources.debug_events.v3alpha.Event events = 3 [json_name = "events"];</code>
     * @param array<\Zitadel\Resources\Debug_events\V3alpha\Event>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zitadel\Resources\Debug_events\V3alpha\Event::class);
        $this->events = $arr;

        return $this;
    }

}

