<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user/v2/user.proto

namespace Zitadel\User\V2;

use UnexpectedValueException;

/**
 * Protobuf type <code>zitadel.user.v2.AuthFactorState</code>
 */
class AuthFactorState
{
    /**
     * Generated from protobuf enum <code>AUTH_FACTOR_STATE_UNSPECIFIED = 0;</code>
     */
    const AUTH_FACTOR_STATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>AUTH_FACTOR_STATE_NOT_READY = 1;</code>
     */
    const AUTH_FACTOR_STATE_NOT_READY = 1;
    /**
     * Generated from protobuf enum <code>AUTH_FACTOR_STATE_READY = 2;</code>
     */
    const AUTH_FACTOR_STATE_READY = 2;
    /**
     * Generated from protobuf enum <code>AUTH_FACTOR_STATE_REMOVED = 3;</code>
     */
    const AUTH_FACTOR_STATE_REMOVED = 3;

    private static $valueToName = [
        self::AUTH_FACTOR_STATE_UNSPECIFIED => 'AUTH_FACTOR_STATE_UNSPECIFIED',
        self::AUTH_FACTOR_STATE_NOT_READY => 'AUTH_FACTOR_STATE_NOT_READY',
        self::AUTH_FACTOR_STATE_READY => 'AUTH_FACTOR_STATE_READY',
        self::AUTH_FACTOR_STATE_REMOVED => 'AUTH_FACTOR_STATE_REMOVED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

