<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user/v2/user_service.proto

namespace Zitadel\User\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.user.v2.ResendEmailCodeRequest</code>
 */
class ResendEmailCodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $user_id = '';
    protected $verification;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type \Zitadel\User\V2\SendEmailVerificationCode $send_code
     *     @type \Zitadel\User\V2\ReturnEmailVerificationCode $return_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\User\V2\UserService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v2.SendEmailVerificationCode send_code = 2 [json_name = "sendCode"];</code>
     * @return \Zitadel\User\V2\SendEmailVerificationCode|null
     */
    public function getSendCode()
    {
        return $this->readOneof(2);
    }

    public function hasSendCode()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v2.SendEmailVerificationCode send_code = 2 [json_name = "sendCode"];</code>
     * @param \Zitadel\User\V2\SendEmailVerificationCode $var
     * @return $this
     */
    public function setSendCode($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V2\SendEmailVerificationCode::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v2.ReturnEmailVerificationCode return_code = 3 [json_name = "returnCode"];</code>
     * @return \Zitadel\User\V2\ReturnEmailVerificationCode|null
     */
    public function getReturnCode()
    {
        return $this->readOneof(3);
    }

    public function hasReturnCode()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v2.ReturnEmailVerificationCode return_code = 3 [json_name = "returnCode"];</code>
     * @param \Zitadel\User\V2\ReturnEmailVerificationCode $var
     * @return $this
     */
    public function setReturnCode($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V2\ReturnEmailVerificationCode::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVerification()
    {
        return $this->whichOneof("verification");
    }

}

