<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/instance.proto

namespace Zitadel\Instance\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.instance.v1.Query</code>
 */
class Query extends \Google\Protobuf\Internal\Message
{
    protected $query;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Instance\V1\IdsQuery $id_query
     *     @type \Zitadel\Instance\V1\DomainsQuery $domain_query
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Instance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.instance.v1.IdsQuery id_query = 1 [json_name = "idQuery"];</code>
     * @return \Zitadel\Instance\V1\IdsQuery|null
     */
    public function getIdQuery()
    {
        return $this->readOneof(1);
    }

    public function hasIdQuery()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.zitadel.instance.v1.IdsQuery id_query = 1 [json_name = "idQuery"];</code>
     * @param \Zitadel\Instance\V1\IdsQuery $var
     * @return $this
     */
    public function setIdQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Instance\V1\IdsQuery::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.instance.v1.DomainsQuery domain_query = 2 [json_name = "domainQuery"];</code>
     * @return \Zitadel\Instance\V1\DomainsQuery|null
     */
    public function getDomainQuery()
    {
        return $this->readOneof(2);
    }

    public function hasDomainQuery()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.zitadel.instance.v1.DomainsQuery domain_query = 2 [json_name = "domainQuery"];</code>
     * @param \Zitadel\Instance\V1\DomainsQuery $var
     * @return $this
     */
    public function setDomainQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Instance\V1\DomainsQuery::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getQuery()
    {
        return $this->whichOneof("query");
    }

}

