<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/action/v3alpha/query.proto

namespace Zitadel\Resources\Action\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.action.v3alpha.ExecutionSearchFilter</code>
 */
class ExecutionSearchFilter extends \Google\Protobuf\Internal\Message
{
    protected $filter;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Resources\Action\V3alpha\InConditionsFilter $in_conditions_filter
     *     @type \Zitadel\Resources\Action\V3alpha\ExecutionTypeFilter $execution_type_filter
     *     @type \Zitadel\Resources\Action\V3alpha\TargetFilter $target_filter
     *     @type \Zitadel\Resources\Action\V3alpha\IncludeFilter $include_filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Action\V3Alpha\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.InConditionsFilter in_conditions_filter = 1 [json_name = "inConditionsFilter"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\InConditionsFilter|null
     */
    public function getInConditionsFilter()
    {
        return $this->readOneof(1);
    }

    public function hasInConditionsFilter()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.InConditionsFilter in_conditions_filter = 1 [json_name = "inConditionsFilter"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\InConditionsFilter $var
     * @return $this
     */
    public function setInConditionsFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\InConditionsFilter::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.ExecutionTypeFilter execution_type_filter = 2 [json_name = "executionTypeFilter"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\ExecutionTypeFilter|null
     */
    public function getExecutionTypeFilter()
    {
        return $this->readOneof(2);
    }

    public function hasExecutionTypeFilter()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.ExecutionTypeFilter execution_type_filter = 2 [json_name = "executionTypeFilter"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\ExecutionTypeFilter $var
     * @return $this
     */
    public function setExecutionTypeFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\ExecutionTypeFilter::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.TargetFilter target_filter = 3 [json_name = "targetFilter"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\TargetFilter|null
     */
    public function getTargetFilter()
    {
        return $this->readOneof(3);
    }

    public function hasTargetFilter()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.TargetFilter target_filter = 3 [json_name = "targetFilter"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\TargetFilter $var
     * @return $this
     */
    public function setTargetFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\TargetFilter::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.IncludeFilter include_filter = 4 [json_name = "includeFilter"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\IncludeFilter|null
     */
    public function getIncludeFilter()
    {
        return $this->readOneof(4);
    }

    public function hasIncludeFilter()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.IncludeFilter include_filter = 4 [json_name = "includeFilter"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\IncludeFilter $var
     * @return $this
     */
    public function setIncludeFilter($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\IncludeFilter::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getFilter()
    {
        return $this->whichOneof("filter");
    }

}

