<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/action/v3alpha/target.proto

namespace Zitadel\Resources\Action\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.action.v3alpha.GetTarget</code>
 */
class GetTarget extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zitadel.resources.object.v3alpha.Details details = 1 [json_name = "details"];</code>
     */
    protected $details = null;
    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Target config = 2 [json_name = "config"];</code>
     */
    protected $config = null;
    /**
     * Generated from protobuf field <code>string signing_key = 3 [json_name = "signingKey", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $signing_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Resources\Object\V3alpha\Details $details
     *     @type \Zitadel\Resources\Action\V3alpha\Target $config
     *     @type string $signing_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Action\V3Alpha\Target::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.object.v3alpha.Details details = 1 [json_name = "details"];</code>
     * @return \Zitadel\Resources\Object\V3alpha\Details|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.object.v3alpha.Details details = 1 [json_name = "details"];</code>
     * @param \Zitadel\Resources\Object\V3alpha\Details $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Object\V3alpha\Details::class);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Target config = 2 [json_name = "config"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\Target|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Target config = 2 [json_name = "config"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\Target $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\Target::class);
        $this->config = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signing_key = 3 [json_name = "signingKey", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getSigningKey()
    {
        return $this->signing_key;
    }

    /**
     * Generated from protobuf field <code>string signing_key = 3 [json_name = "signingKey", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSigningKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->signing_key = $var;

        return $this;
    }

}

