<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/action/v3alpha/action_service.proto

namespace Zitadel\Resources\Action\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.action.v3alpha.SetExecutionRequest</code>
 */
class SetExecutionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $instance = null;
    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Condition condition = 2 [json_name = "condition"];</code>
     */
    protected $condition = null;
    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Execution execution = 3 [json_name = "execution"];</code>
     */
    protected $execution = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Object\V3alpha\Instance $instance
     *     @type \Zitadel\Resources\Action\V3alpha\Condition $condition
     *     @type \Zitadel\Resources\Action\V3alpha\Execution $execution
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Action\V3Alpha\ActionService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Zitadel\Object\V3alpha\Instance|null
     */
    public function getInstance()
    {
        return $this->instance;
    }

    public function hasInstance()
    {
        return isset($this->instance);
    }

    public function clearInstance()
    {
        unset($this->instance);
    }

    /**
     * Generated from protobuf field <code>optional .zitadel.object.v3alpha.Instance instance = 1 [json_name = "instance", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Zitadel\Object\V3alpha\Instance $var
     * @return $this
     */
    public function setInstance($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Object\V3alpha\Instance::class);
        $this->instance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Condition condition = 2 [json_name = "condition"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\Condition|null
     */
    public function getCondition()
    {
        return $this->condition;
    }

    public function hasCondition()
    {
        return isset($this->condition);
    }

    public function clearCondition()
    {
        unset($this->condition);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Condition condition = 2 [json_name = "condition"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\Condition $var
     * @return $this
     */
    public function setCondition($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\Condition::class);
        $this->condition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Execution execution = 3 [json_name = "execution"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\Execution|null
     */
    public function getExecution()
    {
        return $this->execution;
    }

    public function hasExecution()
    {
        return isset($this->execution);
    }

    public function clearExecution()
    {
        unset($this->execution);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.Execution execution = 3 [json_name = "execution"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\Execution $var
     * @return $this
     */
    public function setExecution($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\Execution::class);
        $this->execution = $var;

        return $this;
    }

}

