<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/action/v3alpha/target.proto

namespace Zitadel\Resources\Action\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.action.v3alpha.Target</code>
 */
class Target extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $name = '';
    /**
     * Timeout defines the duration until ZITADEL cancels the execution.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration timeout = 5 [json_name = "timeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $timeout = null;
    /**
     * Generated from protobuf field <code>string endpoint = 6 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $endpoint = '';
    protected $target_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Zitadel\Resources\Action\V3alpha\SetRESTWebhook $rest_webhook
     *     @type \Zitadel\Resources\Action\V3alpha\SetRESTCall $rest_call
     *     @type \Zitadel\Resources\Action\V3alpha\SetRESTAsync $rest_async
     *     @type \Google\Protobuf\Duration $timeout
     *           Timeout defines the duration until ZITADEL cancels the execution.
     *     @type string $endpoint
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Action\V3Alpha\Target::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.SetRESTWebhook rest_webhook = 2 [json_name = "restWebhook"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\SetRESTWebhook|null
     */
    public function getRestWebhook()
    {
        return $this->readOneof(2);
    }

    public function hasRestWebhook()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.SetRESTWebhook rest_webhook = 2 [json_name = "restWebhook"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\SetRESTWebhook $var
     * @return $this
     */
    public function setRestWebhook($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\SetRESTWebhook::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.SetRESTCall rest_call = 3 [json_name = "restCall"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\SetRESTCall|null
     */
    public function getRestCall()
    {
        return $this->readOneof(3);
    }

    public function hasRestCall()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.SetRESTCall rest_call = 3 [json_name = "restCall"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\SetRESTCall $var
     * @return $this
     */
    public function setRestCall($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\SetRESTCall::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.SetRESTAsync rest_async = 4 [json_name = "restAsync"];</code>
     * @return \Zitadel\Resources\Action\V3alpha\SetRESTAsync|null
     */
    public function getRestAsync()
    {
        return $this->readOneof(4);
    }

    public function hasRestAsync()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.zitadel.resources.action.v3alpha.SetRESTAsync rest_async = 4 [json_name = "restAsync"];</code>
     * @param \Zitadel\Resources\Action\V3alpha\SetRESTAsync $var
     * @return $this
     */
    public function setRestAsync($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Resources\Action\V3alpha\SetRESTAsync::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Timeout defines the duration until ZITADEL cancels the execution.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration timeout = 5 [json_name = "timeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    public function hasTimeout()
    {
        return isset($this->timeout);
    }

    public function clearTimeout()
    {
        unset($this->timeout);
    }

    /**
     * Timeout defines the duration until ZITADEL cancels the execution.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration timeout = 5 [json_name = "timeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 6 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 6 [json_name = "endpoint", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getTargetType()
    {
        return $this->whichOneof("target_type");
    }

}

