<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user.proto

namespace Zitadel\User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * this query always equals
 *
 * Generated from protobuf message <code>zitadel.user.v1.MembershipProjectGrantQuery</code>
 */
class MembershipProjectGrantQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string project_grant_id = 1 [json_name = "projectGrantId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $project_grant_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $project_grant_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string project_grant_id = 1 [json_name = "projectGrantId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getProjectGrantId()
    {
        return $this->project_grant_id;
    }

    /**
     * Generated from protobuf field <code>string project_grant_id = 1 [json_name = "projectGrantId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setProjectGrantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_grant_id = $var;

        return $this;
    }

}

