<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user.proto

namespace Zitadel\User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * this query always equals
 *
 * Generated from protobuf message <code>zitadel.user.v1.MembershipIAMQuery</code>
 */
class MembershipIAMQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool iam = 1 [json_name = "iam"];</code>
     */
    protected $iam = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $iam
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool iam = 1 [json_name = "iam"];</code>
     * @return bool
     */
    public function getIam()
    {
        return $this->iam;
    }

    /**
     * Generated from protobuf field <code>bool iam = 1 [json_name = "iam"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIam($var)
    {
        GPBUtil::checkBool($var);
        $this->iam = $var;

        return $this;
    }

}

