<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user.proto

namespace Zitadel\User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.user.v1.UserGrantQuery</code>
 */
class UserGrantQuery extends \Google\Protobuf\Internal\Message
{
    protected $query;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\User\V1\UserGrantProjectIDQuery $project_id_query
     *     @type \Zitadel\User\V1\UserGrantUserIDQuery $user_id_query
     *     @type \Zitadel\User\V1\UserGrantWithGrantedQuery $with_granted_query
     *     @type \Zitadel\User\V1\UserGrantRoleKeyQuery $role_key_query
     *     @type \Zitadel\User\V1\UserGrantProjectGrantIDQuery $project_grant_id_query
     *     @type \Zitadel\User\V1\UserGrantUserNameQuery $user_name_query
     *     @type \Zitadel\User\V1\UserGrantFirstNameQuery $first_name_query
     *     @type \Zitadel\User\V1\UserGrantLastNameQuery $last_name_query
     *     @type \Zitadel\User\V1\UserGrantEmailQuery $email_query
     *     @type \Zitadel\User\V1\UserGrantOrgNameQuery $org_name_query
     *     @type \Zitadel\User\V1\UserGrantOrgDomainQuery $org_domain_query
     *     @type \Zitadel\User\V1\UserGrantProjectNameQuery $project_name_query
     *     @type \Zitadel\User\V1\UserGrantDisplayNameQuery $display_name_query
     *     @type \Zitadel\User\V1\UserGrantUserTypeQuery $user_type_query
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantProjectIDQuery project_id_query = 1 [json_name = "projectIdQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantProjectIDQuery|null
     */
    public function getProjectIdQuery()
    {
        return $this->readOneof(1);
    }

    public function hasProjectIdQuery()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantProjectIDQuery project_id_query = 1 [json_name = "projectIdQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantProjectIDQuery $var
     * @return $this
     */
    public function setProjectIdQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantProjectIDQuery::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantUserIDQuery user_id_query = 2 [json_name = "userIdQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantUserIDQuery|null
     */
    public function getUserIdQuery()
    {
        return $this->readOneof(2);
    }

    public function hasUserIdQuery()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantUserIDQuery user_id_query = 2 [json_name = "userIdQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantUserIDQuery $var
     * @return $this
     */
    public function setUserIdQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantUserIDQuery::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantWithGrantedQuery with_granted_query = 3 [json_name = "withGrantedQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantWithGrantedQuery|null
     */
    public function getWithGrantedQuery()
    {
        return $this->readOneof(3);
    }

    public function hasWithGrantedQuery()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantWithGrantedQuery with_granted_query = 3 [json_name = "withGrantedQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantWithGrantedQuery $var
     * @return $this
     */
    public function setWithGrantedQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantWithGrantedQuery::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantRoleKeyQuery role_key_query = 4 [json_name = "roleKeyQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantRoleKeyQuery|null
     */
    public function getRoleKeyQuery()
    {
        return $this->readOneof(4);
    }

    public function hasRoleKeyQuery()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantRoleKeyQuery role_key_query = 4 [json_name = "roleKeyQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantRoleKeyQuery $var
     * @return $this
     */
    public function setRoleKeyQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantRoleKeyQuery::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantProjectGrantIDQuery project_grant_id_query = 5 [json_name = "projectGrantIdQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantProjectGrantIDQuery|null
     */
    public function getProjectGrantIdQuery()
    {
        return $this->readOneof(5);
    }

    public function hasProjectGrantIdQuery()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantProjectGrantIDQuery project_grant_id_query = 5 [json_name = "projectGrantIdQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantProjectGrantIDQuery $var
     * @return $this
     */
    public function setProjectGrantIdQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantProjectGrantIDQuery::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantUserNameQuery user_name_query = 6 [json_name = "userNameQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantUserNameQuery|null
     */
    public function getUserNameQuery()
    {
        return $this->readOneof(6);
    }

    public function hasUserNameQuery()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantUserNameQuery user_name_query = 6 [json_name = "userNameQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantUserNameQuery $var
     * @return $this
     */
    public function setUserNameQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantUserNameQuery::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantFirstNameQuery first_name_query = 7 [json_name = "firstNameQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantFirstNameQuery|null
     */
    public function getFirstNameQuery()
    {
        return $this->readOneof(7);
    }

    public function hasFirstNameQuery()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantFirstNameQuery first_name_query = 7 [json_name = "firstNameQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantFirstNameQuery $var
     * @return $this
     */
    public function setFirstNameQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantFirstNameQuery::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantLastNameQuery last_name_query = 8 [json_name = "lastNameQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantLastNameQuery|null
     */
    public function getLastNameQuery()
    {
        return $this->readOneof(8);
    }

    public function hasLastNameQuery()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantLastNameQuery last_name_query = 8 [json_name = "lastNameQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantLastNameQuery $var
     * @return $this
     */
    public function setLastNameQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantLastNameQuery::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantEmailQuery email_query = 9 [json_name = "emailQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantEmailQuery|null
     */
    public function getEmailQuery()
    {
        return $this->readOneof(9);
    }

    public function hasEmailQuery()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantEmailQuery email_query = 9 [json_name = "emailQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantEmailQuery $var
     * @return $this
     */
    public function setEmailQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantEmailQuery::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantOrgNameQuery org_name_query = 10 [json_name = "orgNameQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantOrgNameQuery|null
     */
    public function getOrgNameQuery()
    {
        return $this->readOneof(10);
    }

    public function hasOrgNameQuery()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantOrgNameQuery org_name_query = 10 [json_name = "orgNameQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantOrgNameQuery $var
     * @return $this
     */
    public function setOrgNameQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantOrgNameQuery::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantOrgDomainQuery org_domain_query = 11 [json_name = "orgDomainQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantOrgDomainQuery|null
     */
    public function getOrgDomainQuery()
    {
        return $this->readOneof(11);
    }

    public function hasOrgDomainQuery()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantOrgDomainQuery org_domain_query = 11 [json_name = "orgDomainQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantOrgDomainQuery $var
     * @return $this
     */
    public function setOrgDomainQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantOrgDomainQuery::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantProjectNameQuery project_name_query = 12 [json_name = "projectNameQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantProjectNameQuery|null
     */
    public function getProjectNameQuery()
    {
        return $this->readOneof(12);
    }

    public function hasProjectNameQuery()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantProjectNameQuery project_name_query = 12 [json_name = "projectNameQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantProjectNameQuery $var
     * @return $this
     */
    public function setProjectNameQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantProjectNameQuery::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantDisplayNameQuery display_name_query = 13 [json_name = "displayNameQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantDisplayNameQuery|null
     */
    public function getDisplayNameQuery()
    {
        return $this->readOneof(13);
    }

    public function hasDisplayNameQuery()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantDisplayNameQuery display_name_query = 13 [json_name = "displayNameQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantDisplayNameQuery $var
     * @return $this
     */
    public function setDisplayNameQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantDisplayNameQuery::class);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantUserTypeQuery user_type_query = 14 [json_name = "userTypeQuery"];</code>
     * @return \Zitadel\User\V1\UserGrantUserTypeQuery|null
     */
    public function getUserTypeQuery()
    {
        return $this->readOneof(14);
    }

    public function hasUserTypeQuery()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserGrantUserTypeQuery user_type_query = 14 [json_name = "userTypeQuery"];</code>
     * @param \Zitadel\User\V1\UserGrantUserTypeQuery $var
     * @return $this
     */
    public function setUserTypeQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\UserGrantUserTypeQuery::class);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getQuery()
    {
        return $this->whichOneof("query");
    }

}

