<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user.proto

namespace Zitadel\User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.user.v1.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 2 [json_name = "details"];</code>
     */
    protected $details = null;
    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserState state = 3 [json_name = "state", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>string user_name = 4 [json_name = "userName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $user_name = '';
    /**
     * Generated from protobuf field <code>repeated string login_names = 5 [json_name = "loginNames", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $login_names;
    /**
     * Generated from protobuf field <code>string preferred_login_name = 6 [json_name = "preferredLoginName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $preferred_login_name = '';
    protected $type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Zitadel\V1\ObjectDetails $details
     *     @type int $state
     *     @type string $user_name
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $login_names
     *     @type string $preferred_login_name
     *     @type \Zitadel\User\V1\Human $human
     *     @type \Zitadel\User\V1\Machine $machine
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 2 [json_name = "details"];</code>
     * @return \Zitadel\V1\ObjectDetails|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Generated from protobuf field <code>.zitadel.v1.ObjectDetails details = 2 [json_name = "details"];</code>
     * @param \Zitadel\V1\ObjectDetails $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\V1\ObjectDetails::class);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserState state = 3 [json_name = "state", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.UserState state = 3 [json_name = "state", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Zitadel\User\V1\UserState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_name = 4 [json_name = "userName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     * Generated from protobuf field <code>string user_name = 4 [json_name = "userName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string login_names = 5 [json_name = "loginNames", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLoginNames()
    {
        return $this->login_names;
    }

    /**
     * Generated from protobuf field <code>repeated string login_names = 5 [json_name = "loginNames", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLoginNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->login_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string preferred_login_name = 6 [json_name = "preferredLoginName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getPreferredLoginName()
    {
        return $this->preferred_login_name;
    }

    /**
     * Generated from protobuf field <code>string preferred_login_name = 6 [json_name = "preferredLoginName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPreferredLoginName($var)
    {
        GPBUtil::checkString($var, True);
        $this->preferred_login_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.Human human = 7 [json_name = "human", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Zitadel\User\V1\Human|null
     */
    public function getHuman()
    {
        return $this->readOneof(7);
    }

    public function hasHuman()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.Human human = 7 [json_name = "human", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Zitadel\User\V1\Human $var
     * @return $this
     */
    public function setHuman($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\Human::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.Machine machine = 8 [json_name = "machine", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Zitadel\User\V1\Machine|null
     */
    public function getMachine()
    {
        return $this->readOneof(8);
    }

    public function hasMachine()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v1.Machine machine = 8 [json_name = "machine", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Zitadel\User\V1\Machine $var
     * @return $this
     */
    public function setMachine($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V1\Machine::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->whichOneof("type");
    }

}

