<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user.proto

namespace Zitadel\User\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>zitadel.user.v1.UserFieldName</code>
 */
class UserFieldName
{
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_UNSPECIFIED = 0;</code>
     */
    const USER_FIELD_NAME_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_USER_NAME = 1;</code>
     */
    const USER_FIELD_NAME_USER_NAME = 1;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_FIRST_NAME = 2;</code>
     */
    const USER_FIELD_NAME_FIRST_NAME = 2;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_LAST_NAME = 3;</code>
     */
    const USER_FIELD_NAME_LAST_NAME = 3;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_NICK_NAME = 4;</code>
     */
    const USER_FIELD_NAME_NICK_NAME = 4;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_DISPLAY_NAME = 5;</code>
     */
    const USER_FIELD_NAME_DISPLAY_NAME = 5;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_EMAIL = 6;</code>
     */
    const USER_FIELD_NAME_EMAIL = 6;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_STATE = 7;</code>
     */
    const USER_FIELD_NAME_STATE = 7;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_TYPE = 8;</code>
     */
    const USER_FIELD_NAME_TYPE = 8;
    /**
     * Generated from protobuf enum <code>USER_FIELD_NAME_CREATION_DATE = 9;</code>
     */
    const USER_FIELD_NAME_CREATION_DATE = 9;

    private static $valueToName = [
        self::USER_FIELD_NAME_UNSPECIFIED => 'USER_FIELD_NAME_UNSPECIFIED',
        self::USER_FIELD_NAME_USER_NAME => 'USER_FIELD_NAME_USER_NAME',
        self::USER_FIELD_NAME_FIRST_NAME => 'USER_FIELD_NAME_FIRST_NAME',
        self::USER_FIELD_NAME_LAST_NAME => 'USER_FIELD_NAME_LAST_NAME',
        self::USER_FIELD_NAME_NICK_NAME => 'USER_FIELD_NAME_NICK_NAME',
        self::USER_FIELD_NAME_DISPLAY_NAME => 'USER_FIELD_NAME_DISPLAY_NAME',
        self::USER_FIELD_NAME_EMAIL => 'USER_FIELD_NAME_EMAIL',
        self::USER_FIELD_NAME_STATE => 'USER_FIELD_NAME_STATE',
        self::USER_FIELD_NAME_TYPE => 'USER_FIELD_NAME_TYPE',
        self::USER_FIELD_NAME_CREATION_DATE => 'USER_FIELD_NAME_CREATION_DATE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

