<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/session/v2beta/session_service.proto

namespace Zitadel\Session\V2beta;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.session.v2beta.ListSessionsRequest</code>
 */
class ListSessionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zitadel.object.v2beta.ListQuery query = 1 [json_name = "query"];</code>
     */
    protected $query = null;
    /**
     * Generated from protobuf field <code>repeated .zitadel.session.v2beta.SearchQuery queries = 2 [json_name = "queries"];</code>
     */
    private $queries;
    /**
     * Generated from protobuf field <code>.zitadel.session.v2beta.SessionFieldName sorting_column = 3 [json_name = "sortingColumn"];</code>
     */
    protected $sorting_column = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Object\V2beta\ListQuery $query
     *     @type array<\Zitadel\Session\V2beta\SearchQuery>|\Google\Protobuf\Internal\RepeatedField $queries
     *     @type int $sorting_column
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Session\V2Beta\SessionService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.object.v2beta.ListQuery query = 1 [json_name = "query"];</code>
     * @return \Zitadel\Object\V2beta\ListQuery|null
     */
    public function getQuery()
    {
        return $this->query;
    }

    public function hasQuery()
    {
        return isset($this->query);
    }

    public function clearQuery()
    {
        unset($this->query);
    }

    /**
     * Generated from protobuf field <code>.zitadel.object.v2beta.ListQuery query = 1 [json_name = "query"];</code>
     * @param \Zitadel\Object\V2beta\ListQuery $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Object\V2beta\ListQuery::class);
        $this->query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.session.v2beta.SearchQuery queries = 2 [json_name = "queries"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQueries()
    {
        return $this->queries;
    }

    /**
     * Generated from protobuf field <code>repeated .zitadel.session.v2beta.SearchQuery queries = 2 [json_name = "queries"];</code>
     * @param array<\Zitadel\Session\V2beta\SearchQuery>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQueries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zitadel\Session\V2beta\SearchQuery::class);
        $this->queries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.session.v2beta.SessionFieldName sorting_column = 3 [json_name = "sortingColumn"];</code>
     * @return int
     */
    public function getSortingColumn()
    {
        return $this->sorting_column;
    }

    /**
     * Generated from protobuf field <code>.zitadel.session.v2beta.SessionFieldName sorting_column = 3 [json_name = "sortingColumn"];</code>
     * @param int $var
     * @return $this
     */
    public function setSortingColumn($var)
    {
        GPBUtil::checkEnum($var, \Zitadel\Session\V2beta\SessionFieldName::class);
        $this->sorting_column = $var;

        return $this;
    }

}

