<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/v1.proto

namespace Zitadel\V1\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.v1.v1.DataProject</code>
 */
class DataProject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string project_id = 1 [json_name = "projectId"];</code>
     */
    protected $project_id = '';
    /**
     * Generated from protobuf field <code>.zitadel.management.v1.AddProjectRequest project = 2 [json_name = "project"];</code>
     */
    protected $project = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $project_id
     *     @type \Zitadel\Management\V1\AddProjectRequest $project
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\V1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string project_id = 1 [json_name = "projectId"];</code>
     * @return string
     */
    public function getProjectId()
    {
        return $this->project_id;
    }

    /**
     * Generated from protobuf field <code>string project_id = 1 [json_name = "projectId"];</code>
     * @param string $var
     * @return $this
     */
    public function setProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.management.v1.AddProjectRequest project = 2 [json_name = "project"];</code>
     * @return \Zitadel\Management\V1\AddProjectRequest|null
     */
    public function getProject()
    {
        return $this->project;
    }

    public function hasProject()
    {
        return isset($this->project);
    }

    public function clearProject()
    {
        unset($this->project);
    }

    /**
     * Generated from protobuf field <code>.zitadel.management.v1.AddProjectRequest project = 2 [json_name = "project"];</code>
     * @param \Zitadel\Management\V1\AddProjectRequest $var
     * @return $this
     */
    public function setProject($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Management\V1\AddProjectRequest::class);
        $this->project = $var;

        return $this;
    }

}

