<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user/v2beta/user.proto

namespace Zitadel\User\V2beta;

use UnexpectedValueException;

/**
 * Protobuf type <code>zitadel.user.v2beta.AccessTokenType</code>
 */
class AccessTokenType
{
    /**
     * Generated from protobuf enum <code>ACCESS_TOKEN_TYPE_BEARER = 0;</code>
     */
    const ACCESS_TOKEN_TYPE_BEARER = 0;
    /**
     * Generated from protobuf enum <code>ACCESS_TOKEN_TYPE_JWT = 1;</code>
     */
    const ACCESS_TOKEN_TYPE_JWT = 1;

    private static $valueToName = [
        self::ACCESS_TOKEN_TYPE_BEARER => 'ACCESS_TOKEN_TYPE_BEARER',
        self::ACCESS_TOKEN_TYPE_JWT => 'ACCESS_TOKEN_TYPE_JWT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

