<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user/v2beta/user_service.proto

namespace Zitadel\User\V2beta;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.user.v2beta.AddIDPLinkRequest</code>
 */
class AddIDPLinkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>.zitadel.user.v2beta.IDPLink idp_link = 2 [json_name = "idpLink"];</code>
     */
    protected $idp_link = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type \Zitadel\User\V2beta\IDPLink $idp_link
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\User\V2Beta\UserService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v2beta.IDPLink idp_link = 2 [json_name = "idpLink"];</code>
     * @return \Zitadel\User\V2beta\IDPLink|null
     */
    public function getIdpLink()
    {
        return $this->idp_link;
    }

    public function hasIdpLink()
    {
        return isset($this->idp_link);
    }

    public function clearIdpLink()
    {
        unset($this->idp_link);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v2beta.IDPLink idp_link = 2 [json_name = "idpLink"];</code>
     * @param \Zitadel\User\V2beta\IDPLink $var
     * @return $this
     */
    public function setIdpLink($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V2beta\IDPLink::class);
        $this->idp_link = $var;

        return $this;
    }

}

