<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/user/v2beta/user_service.proto

namespace Zitadel\User\V2beta;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.user.v2beta.StartIdentityProviderIntentResponse</code>
 */
class StartIdentityProviderIntentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zitadel.object.v2beta.Details details = 1 [json_name = "details"];</code>
     */
    protected $details = null;
    protected $next_step;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Object\V2beta\Details $details
     *     @type string $auth_url
     *     @type \Zitadel\User\V2beta\IDPIntent $idp_intent
     *     @type string $post_form
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\User\V2Beta\UserService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.object.v2beta.Details details = 1 [json_name = "details"];</code>
     * @return \Zitadel\Object\V2beta\Details|null
     */
    public function getDetails()
    {
        return $this->details;
    }

    public function hasDetails()
    {
        return isset($this->details);
    }

    public function clearDetails()
    {
        unset($this->details);
    }

    /**
     * Generated from protobuf field <code>.zitadel.object.v2beta.Details details = 1 [json_name = "details"];</code>
     * @param \Zitadel\Object\V2beta\Details $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Object\V2beta\Details::class);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string auth_url = 2 [json_name = "authUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getAuthUrl()
    {
        return $this->readOneof(2);
    }

    public function hasAuthUrl()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string auth_url = 2 [json_name = "authUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setAuthUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v2beta.IDPIntent idp_intent = 3 [json_name = "idpIntent", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Zitadel\User\V2beta\IDPIntent|null
     */
    public function getIdpIntent()
    {
        return $this->readOneof(3);
    }

    public function hasIdpIntent()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.zitadel.user.v2beta.IDPIntent idp_intent = 3 [json_name = "idpIntent", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Zitadel\User\V2beta\IDPIntent $var
     * @return $this
     */
    public function setIdpIntent($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\User\V2beta\IDPIntent::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes post_form = 4 [json_name = "postForm", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getPostForm()
    {
        return $this->readOneof(4);
    }

    public function hasPostForm()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>bytes post_form = 4 [json_name = "postForm", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPostForm($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getNextStep()
    {
        return $this->whichOneof("next_step");
    }

}

