<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/metadata.proto

namespace Zitadel\Metadata\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.metadata.v1.MetadataQuery</code>
 */
class MetadataQuery extends \Google\Protobuf\Internal\Message
{
    protected $query;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\Metadata\V1\MetadataKeyQuery $key_query
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Metadata::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.metadata.v1.MetadataKeyQuery key_query = 1 [json_name = "keyQuery"];</code>
     * @return \Zitadel\Metadata\V1\MetadataKeyQuery|null
     */
    public function getKeyQuery()
    {
        return $this->readOneof(1);
    }

    public function hasKeyQuery()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.zitadel.metadata.v1.MetadataKeyQuery key_query = 1 [json_name = "keyQuery"];</code>
     * @param \Zitadel\Metadata\V1\MetadataKeyQuery $var
     * @return $this
     */
    public function setKeyQuery($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Metadata\V1\MetadataKeyQuery::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getQuery()
    {
        return $this->whichOneof("query");
    }

}

