<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/options.proto

namespace Zitadel\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.v1.AuthOption</code>
 */
class AuthOption extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string permission = 1 [json_name = "permission"];</code>
     */
    protected $permission = '';
    /**
     * Generated from protobuf field <code>string check_field_name = 2 [json_name = "checkFieldName"];</code>
     */
    protected $check_field_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $permission
     *     @type string $check_field_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Options::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string permission = 1 [json_name = "permission"];</code>
     * @return string
     */
    public function getPermission()
    {
        return $this->permission;
    }

    /**
     * Generated from protobuf field <code>string permission = 1 [json_name = "permission"];</code>
     * @param string $var
     * @return $this
     */
    public function setPermission($var)
    {
        GPBUtil::checkString($var, True);
        $this->permission = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string check_field_name = 2 [json_name = "checkFieldName"];</code>
     * @return string
     */
    public function getCheckFieldName()
    {
        return $this->check_field_name;
    }

    /**
     * Generated from protobuf field <code>string check_field_name = 2 [json_name = "checkFieldName"];</code>
     * @param string $var
     * @return $this
     */
    public function setCheckFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->check_field_name = $var;

        return $this;
    }

}

