<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/settings/v2beta/settings.proto

namespace GPBMetadata\Zitadel\Settings\V2Beta;

class Settings
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ProtocGenOpenapiv2\Options\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x82\x02\x0A&zitadel/settings/v2beta/settings.proto\x12\x17zitadel.settings.v2beta*w\x0A\x11ResourceOwnerType\x12#\x0A\x1FRESOURCE_OWNER_TYPE_UNSPECIFIED\x10\x00\x12 \x0A\x1CRESOURCE_OWNER_TYPE_INSTANCE\x10\x01\x12\x1B\x0A\x17RESOURCE_OWNER_TYPE_ORG\x10\x02B>Z<github.com/zitadel/zitadel/pkg/grpc/settings/v2beta;settingsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

