<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/app.proto

namespace Zitadel\App\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.app.v1.LoginVersion</code>
 */
class LoginVersion extends \Google\Protobuf\Internal\Message
{
    protected $version;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zitadel\App\V1\LoginV1 $login_v1
     *     @type \Zitadel\App\V1\LoginV2 $login_v2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\App::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zitadel.app.v1.LoginV1 login_v1 = 1 [json_name = "loginV1"];</code>
     * @return \Zitadel\App\V1\LoginV1|null
     */
    public function getLoginV1()
    {
        return $this->readOneof(1);
    }

    public function hasLoginV1()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.zitadel.app.v1.LoginV1 login_v1 = 1 [json_name = "loginV1"];</code>
     * @param \Zitadel\App\V1\LoginV1 $var
     * @return $this
     */
    public function setLoginV1($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\App\V1\LoginV1::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zitadel.app.v1.LoginV2 login_v2 = 2 [json_name = "loginV2"];</code>
     * @return \Zitadel\App\V1\LoginV2|null
     */
    public function getLoginV2()
    {
        return $this->readOneof(2);
    }

    public function hasLoginV2()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.zitadel.app.v1.LoginV2 login_v2 = 2 [json_name = "loginV2"];</code>
     * @param \Zitadel\App\V1\LoginV2 $var
     * @return $this
     */
    public function setLoginV2($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\App\V1\LoginV2::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getVersion()
    {
        return $this->whichOneof("version");
    }

}

