<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/app.proto

namespace Zitadel\App\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>zitadel.app.v1.OIDCVersion</code>
 */
class OIDCVersion
{
    /**
     * Generated from protobuf enum <code>OIDC_VERSION_1_0 = 0;</code>
     */
    const OIDC_VERSION_1_0 = 0;

    private static $valueToName = [
        self::OIDC_VERSION_1_0 => 'OIDC_VERSION_1_0',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

