<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/app.proto

namespace Zitadel\App\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>zitadel.app.v1.OIDCAuthMethodType</code>
 */
class OIDCAuthMethodType
{
    /**
     * Generated from protobuf enum <code>OIDC_AUTH_METHOD_TYPE_BASIC = 0;</code>
     */
    const OIDC_AUTH_METHOD_TYPE_BASIC = 0;
    /**
     * Generated from protobuf enum <code>OIDC_AUTH_METHOD_TYPE_POST = 1;</code>
     */
    const OIDC_AUTH_METHOD_TYPE_POST = 1;
    /**
     * Generated from protobuf enum <code>OIDC_AUTH_METHOD_TYPE_NONE = 2;</code>
     */
    const OIDC_AUTH_METHOD_TYPE_NONE = 2;
    /**
     * Generated from protobuf enum <code>OIDC_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT = 3;</code>
     */
    const OIDC_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT = 3;

    private static $valueToName = [
        self::OIDC_AUTH_METHOD_TYPE_BASIC => 'OIDC_AUTH_METHOD_TYPE_BASIC',
        self::OIDC_AUTH_METHOD_TYPE_POST => 'OIDC_AUTH_METHOD_TYPE_POST',
        self::OIDC_AUTH_METHOD_TYPE_NONE => 'OIDC_AUTH_METHOD_TYPE_NONE',
        self::OIDC_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT => 'OIDC_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

