<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zitadel/resources/object/v3alpha/object.proto

namespace Zitadel\Resources\Object\V3alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zitadel.resources.object.v3alpha.Details</code>
 */
class Details extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $id = '';
    /**
     *the timestamp of the first event applied to the object.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 3 [json_name = "created"];</code>
     */
    protected $created = null;
    /**
     *the timestamp of the last event applied to the object.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp changed = 4 [json_name = "changed"];</code>
     */
    protected $changed = null;
    /**
     *the parent object representing the returned objects context.
     *
     * Generated from protobuf field <code>.zitadel.object.v3alpha.Owner owner = 5 [json_name = "owner", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $owner = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Google\Protobuf\Timestamp $created
     *          the timestamp of the first event applied to the object.
     *     @type \Google\Protobuf\Timestamp $changed
     *          the timestamp of the last event applied to the object.
     *     @type \Zitadel\Object\V3alpha\Owner $owner
     *          the parent object representing the returned objects context.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Zitadel\Resources\Object\V3Alpha\Object::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     *the timestamp of the first event applied to the object.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 3 [json_name = "created"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreated()
    {
        return $this->created;
    }

    public function hasCreated()
    {
        return isset($this->created);
    }

    public function clearCreated()
    {
        unset($this->created);
    }

    /**
     *the timestamp of the first event applied to the object.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 3 [json_name = "created"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created = $var;

        return $this;
    }

    /**
     *the timestamp of the last event applied to the object.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp changed = 4 [json_name = "changed"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getChanged()
    {
        return $this->changed;
    }

    public function hasChanged()
    {
        return isset($this->changed);
    }

    public function clearChanged()
    {
        unset($this->changed);
    }

    /**
     *the timestamp of the last event applied to the object.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp changed = 4 [json_name = "changed"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setChanged($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->changed = $var;

        return $this;
    }

    /**
     *the parent object representing the returned objects context.
     *
     * Generated from protobuf field <code>.zitadel.object.v3alpha.Owner owner = 5 [json_name = "owner", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Zitadel\Object\V3alpha\Owner|null
     */
    public function getOwner()
    {
        return $this->owner;
    }

    public function hasOwner()
    {
        return isset($this->owner);
    }

    public function clearOwner()
    {
        unset($this->owner);
    }

    /**
     *the parent object representing the returned objects context.
     *
     * Generated from protobuf field <code>.zitadel.object.v3alpha.Owner owner = 5 [json_name = "owner", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Zitadel\Object\V3alpha\Owner $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkMessage($var, \Zitadel\Object\V3alpha\Owner::class);
        $this->owner = $var;

        return $this;
    }

}

